/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthproxySetting
 */
class AuthproxySettingTest {
    private final AuthproxySetting model = new AuthproxySetting();

    /**
     * Model tests for AuthproxySetting
     */
    @Test
    void testAuthproxySetting() {
        // TODO: test AuthproxySetting
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'tokenreivewEndpoint'
     */
    @Test
    void tokenreivewEndpointTest() {
        // TODO: test tokenreivewEndpoint
    }

    /**
     * Test the property 'skipSearch'
     */
    @Test
    void skipSearchTest() {
        // TODO: test skipSearch
    }

    /**
     * Test the property 'verifyCert'
     */
    @Test
    void verifyCertTest() {
        // TODO: test verifyCert
    }

    /**
     * Test the property 'serverCertificate'
     */
    @Test
    void serverCertificateTest() {
        // TODO: test serverCertificate
    }

}
