/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.ConfigurationsResponseScanAllPolicyParameter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfigurationsResponseScanAllPolicy
 */
class ConfigurationsResponseScanAllPolicyTest {
    private final ConfigurationsResponseScanAllPolicy model = new ConfigurationsResponseScanAllPolicy();

    /**
     * Model tests for ConfigurationsResponseScanAllPolicy
     */
    @Test
    void testConfigurationsResponseScanAllPolicy() {
        // TODO: test ConfigurationsResponseScanAllPolicy
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'parameter'
     */
    @Test
    void parameterTest() {
        // TODO: test parameter
    }

}
