/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DangerousArtifact
 */
class DangerousArtifactTest {
    private final DangerousArtifact model = new DangerousArtifact();

    /**
     * Model tests for DangerousArtifact
     */
    @Test
    void testDangerousArtifact() {
        // TODO: test DangerousArtifact
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'repositoryName'
     */
    @Test
    void repositoryNameTest() {
        // TODO: test repositoryName
    }

    /**
     * Test the property 'digest'
     */
    @Test
    void digestTest() {
        // TODO: test digest
    }

    /**
     * Test the property 'criticalCnt'
     */
    @Test
    void criticalCntTest() {
        // TODO: test criticalCnt
    }

    /**
     * Test the property 'highCnt'
     */
    @Test
    void highCntTest() {
        // TODO: test highCnt
    }

    /**
     * Test the property 'mediumCnt'
     */
    @Test
    void mediumCntTest() {
        // TODO: test mediumCnt
    }

}
