/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.AuthproxySetting;
import java.util.Date;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GeneralInfo
 */
class GeneralInfoTest {
    private final GeneralInfo model = new GeneralInfo();

    /**
     * Model tests for GeneralInfo
     */
    @Test
    void testGeneralInfo() {
        // TODO: test GeneralInfo
    }

    /**
     * Test the property 'bannerMessage'
     */
    @Test
    void bannerMessageTest() {
        // TODO: test bannerMessage
    }

    /**
     * Test the property 'currentTime'
     */
    @Test
    void currentTimeTest() {
        // TODO: test currentTime
    }

    /**
     * Test the property 'registryUrl'
     */
    @Test
    void registryUrlTest() {
        // TODO: test registryUrl
    }

    /**
     * Test the property 'externalUrl'
     */
    @Test
    void externalUrlTest() {
        // TODO: test externalUrl
    }

    /**
     * Test the property 'authMode'
     */
    @Test
    void authModeTest() {
        // TODO: test authMode
    }

    /**
     * Test the property 'primaryAuthMode'
     */
    @Test
    void primaryAuthModeTest() {
        // TODO: test primaryAuthMode
    }

    /**
     * Test the property 'projectCreationRestriction'
     */
    @Test
    void projectCreationRestrictionTest() {
        // TODO: test projectCreationRestriction
    }

    /**
     * Test the property 'selfRegistration'
     */
    @Test
    void selfRegistrationTest() {
        // TODO: test selfRegistration
    }

    /**
     * Test the property 'hasCaRoot'
     */
    @Test
    void hasCaRootTest() {
        // TODO: test hasCaRoot
    }

    /**
     * Test the property 'harborVersion'
     */
    @Test
    void harborVersionTest() {
        // TODO: test harborVersion
    }

    /**
     * Test the property 'registryStorageProviderName'
     */
    @Test
    void registryStorageProviderNameTest() {
        // TODO: test registryStorageProviderName
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    void readOnlyTest() {
        // TODO: test readOnly
    }

    /**
     * Test the property 'notificationEnable'
     */
    @Test
    void notificationEnableTest() {
        // TODO: test notificationEnable
    }

    /**
     * Test the property 'authproxySettings'
     */
    @Test
    void authproxySettingsTest() {
        // TODO: test authproxySettings
    }

    /**
     * Test the property 'oidcProviderName'
     */
    @Test
    void oidcProviderNameTest() {
        // TODO: test oidcProviderName
    }

}
