/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobQueue
 */
class JobQueueTest {
    private final JobQueue model = new JobQueue();

    /**
     * Model tests for JobQueue
     */
    @Test
    void testJobQueue() {
        // TODO: test JobQueue
    }

    /**
     * Test the property 'jobType'
     */
    @Test
    void jobTypeTest() {
        // TODO: test jobType
    }

    /**
     * Test the property 'count'
     */
    @Test
    void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'latency'
     */
    @Test
    void latencyTest() {
        // TODO: test latency
    }

    /**
     * Test the property 'paused'
     */
    @Test
    void pausedTest() {
        // TODO: test paused
    }

}
