/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PayloadFormat
 */
class PayloadFormatTest {
    private final PayloadFormat model = new PayloadFormat();

    /**
     * Model tests for PayloadFormat
     */
    @Test
    void testPayloadFormat() {
        // TODO: test PayloadFormat
    }

    /**
     * Test the property 'notifyType'
     */
    @Test
    void notifyTypeTest() {
        // TODO: test notifyType
    }

    /**
     * Test the property 'formats'
     */
    @Test
    void formatsTest() {
        // TODO: test formats
    }

}
