/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.Permission;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Permissions
 */
class PermissionsTest {
    private final Permissions model = new Permissions();

    /**
     * Model tests for Permissions
     */
    @Test
    void testPermissions() {
        // TODO: test Permissions
    }

    /**
     * Test the property 'system'
     */
    @Test
    void systemTest() {
        // TODO: test system
    }

    /**
     * Test the property 'project'
     */
    @Test
    void projectTest() {
        // TODO: test project
    }

}
