/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Platform
 */
class PlatformTest {
    private final Platform model = new Platform();

    /**
     * Model tests for Platform
     */
    @Test
    void testPlatform() {
        // TODO: test Platform
    }

    /**
     * Test the property 'architecture'
     */
    @Test
    void architectureTest() {
        // TODO: test architecture
    }

    /**
     * Test the property 'os'
     */
    @Test
    void osTest() {
        // TODO: test os
    }

    /**
     * Test the property 'quoteOsVersionQuote'
     */
    @Test
    void quoteOsVersionQuoteTest() {
        // TODO: test quoteOsVersionQuote
    }

    /**
     * Test the property 'quoteOsFeaturesQuote'
     */
    @Test
    void quoteOsFeaturesQuoteTest() {
        // TODO: test quoteOsFeaturesQuote
    }

    /**
     * Test the property 'variant'
     */
    @Test
    void variantTest() {
        // TODO: test variant
    }

}
