/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PreheatPolicy
 */
class PreheatPolicyTest {
    private final PreheatPolicy model = new PreheatPolicy();

    /**
     * Model tests for PreheatPolicy
     */
    @Test
    void testPreheatPolicy() {
        // TODO: test PreheatPolicy
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'providerId'
     */
    @Test
    void providerIdTest() {
        // TODO: test providerId
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'filters'
     */
    @Test
    void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'trigger'
     */
    @Test
    void triggerTest() {
        // TODO: test trigger
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'extraAttrs'
     */
    @Test
    void extraAttrsTest() {
        // TODO: test extraAttrs
    }

    /**
     * Test the property 'creationTime'
     */
    @Test
    void creationTimeTest() {
        // TODO: test creationTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    void updateTimeTest() {
        // TODO: test updateTime
    }

}
