/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.CVEAllowlist;
import com.ryan.openapi.harbor.client.model.ProjectMetadata;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectReq
 */
class ProjectReqTest {
    private final ProjectReq model = new ProjectReq();

    /**
     * Model tests for ProjectReq
     */
    @Test
    void testProjectReq() {
        // TODO: test ProjectReq
    }

    /**
     * Test the property 'projectName'
     */
    @Test
    void projectNameTest() {
        // TODO: test projectName
    }

    /**
     * Test the property '_public'
     */
    @Test
    void _publicTest() {
        // TODO: test _public
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'cveAllowlist'
     */
    @Test
    void cveAllowlistTest() {
        // TODO: test cveAllowlist
    }

    /**
     * Test the property 'storageLimit'
     */
    @Test
    void storageLimitTest() {
        // TODO: test storageLimit
    }

    /**
     * Test the property 'registryId'
     */
    @Test
    void registryIdTest() {
        // TODO: test registryId
    }

}
