/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.UserEntity;
import com.ryan.openapi.harbor.client.model.UserGroup;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectMember
 */
class ProjectMemberTest {
    private final ProjectMember model = new ProjectMember();

    /**
     * Model tests for ProjectMember
     */
    @Test
    void testProjectMember() {
        // TODO: test ProjectMember
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    void roleIdTest() {
        // TODO: test roleId
    }

    /**
     * Test the property 'memberUser'
     */
    @Test
    void memberUserTest() {
        // TODO: test memberUser
    }

    /**
     * Test the property 'memberGroup'
     */
    @Test
    void memberGroupTest() {
        // TODO: test memberGroup
    }

}
