/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.FilterStyle;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RegistryInfo
 */
class RegistryInfoTest {
    private final RegistryInfo model = new RegistryInfo();

    /**
     * Model tests for RegistryInfo
     */
    @Test
    void testRegistryInfo() {
        // TODO: test RegistryInfo
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'supportedResourceFilters'
     */
    @Test
    void supportedResourceFiltersTest() {
        // TODO: test supportedResourceFilters
    }

    /**
     * Test the property 'supportedTriggers'
     */
    @Test
    void supportedTriggersTest() {
        // TODO: test supportedTriggers
    }

    /**
     * Test the property 'supportedCopyByChunk'
     */
    @Test
    void supportedCopyByChunkTest() {
        // TODO: test supportedCopyByChunk
    }

}
