/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Repository
 */
class RepositoryTest {
    private final Repository model = new Repository();

    /**
     * Model tests for Repository
     */
    @Test
    void testRepository() {
        // TODO: test Repository
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'artifactCount'
     */
    @Test
    void artifactCountTest() {
        // TODO: test artifactCount
    }

    /**
     * Test the property 'pullCount'
     */
    @Test
    void pullCountTest() {
        // TODO: test pullCount
    }

    /**
     * Test the property 'creationTime'
     */
    @Test
    void creationTimeTest() {
        // TODO: test creationTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    void updateTimeTest() {
        // TODO: test updateTime
    }

}
