/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.RetentionSelector;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetentionRule
 */
class RetentionRuleTest {
    private final RetentionRule model = new RetentionRule();

    /**
     * Model tests for RetentionRule
     */
    @Test
    void testRetentionRule() {
        // TODO: test RetentionRule
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'priority'
     */
    @Test
    void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'action'
     */
    @Test
    void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'params'
     */
    @Test
    void paramsTest() {
        // TODO: test params
    }

    /**
     * Test the property 'tagSelectors'
     */
    @Test
    void tagSelectorsTest() {
        // TODO: test tagSelectors
    }

    /**
     * Test the property 'scopeSelectors'
     */
    @Test
    void scopeSelectorsTest() {
        // TODO: test scopeSelectors
    }

}
