/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetentionRuleTrigger
 */
class RetentionRuleTriggerTest {
    private final RetentionRuleTrigger model = new RetentionRuleTrigger();

    /**
     * Model tests for RetentionRuleTrigger
     */
    @Test
    void testRetentionRuleTrigger() {
        // TODO: test RetentionRuleTrigger
    }

    /**
     * Test the property 'kind'
     */
    @Test
    void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'settings'
     */
    @Test
    void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'references'
     */
    @Test
    void referencesTest() {
        // TODO: test references
    }

}
