/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScanDataExportRequest
 */
class ScanDataExportRequestTest {
    private final ScanDataExportRequest model = new ScanDataExportRequest();

    /**
     * Model tests for ScanDataExportRequest
     */
    @Test
    void testScanDataExportRequest() {
        // TODO: test ScanDataExportRequest
    }

    /**
     * Test the property 'jobName'
     */
    @Test
    void jobNameTest() {
        // TODO: test jobName
    }

    /**
     * Test the property 'projects'
     */
    @Test
    void projectsTest() {
        // TODO: test projects
    }

    /**
     * Test the property 'labels'
     */
    @Test
    void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'repositories'
     */
    @Test
    void repositoriesTest() {
        // TODO: test repositories
    }

    /**
     * Test the property 'cveIds'
     */
    @Test
    void cveIdsTest() {
        // TODO: test cveIds
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

}
