/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.Scanner;
import com.ryan.openapi.harbor.client.model.ScannerCapability;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScannerAdapterMetadata
 */
class ScannerAdapterMetadataTest {
    private final ScannerAdapterMetadata model = new ScannerAdapterMetadata();

    /**
     * Model tests for ScannerAdapterMetadata
     */
    @Test
    void testScannerAdapterMetadata() {
        // TODO: test ScannerAdapterMetadata
    }

    /**
     * Test the property 'scanner'
     */
    @Test
    void scannerTest() {
        // TODO: test scanner
    }

    /**
     * Test the property 'capabilities'
     */
    @Test
    void capabilitiesTest() {
        // TODO: test capabilities
    }

    /**
     * Test the property 'properties'
     */
    @Test
    void propertiesTest() {
        // TODO: test properties
    }

}
