/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScannerRegistrationSettings
 */
class ScannerRegistrationSettingsTest {
    private final ScannerRegistrationSettings model = new ScannerRegistrationSettings();

    /**
     * Model tests for ScannerRegistrationSettings
     */
    @Test
    void testScannerRegistrationSettings() {
        // TODO: test ScannerRegistrationSettings
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'auth'
     */
    @Test
    void authTest() {
        // TODO: test auth
    }

    /**
     * Test the property 'accessCredential'
     */
    @Test
    void accessCredentialTest() {
        // TODO: test accessCredential
    }

}
