/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.Project;
import com.ryan.openapi.harbor.client.model.SearchRepository;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Search
 */
class SearchTest {
    private final Search model = new Search();

    /**
     * Model tests for Search
     */
    @Test
    void testSearch() {
        // TODO: test Search
    }

    /**
     * Test the property 'project'
     */
    @Test
    void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'repository'
     */
    @Test
    void repositoryTest() {
        // TODO: test repository
    }

}
