/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.OIDCUserInfo;
import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserResp
 */
class UserRespTest {
    private final UserResp model = new UserResp();

    /**
     * Model tests for UserResp
     */
    @Test
    void testUserResp() {
        // TODO: test UserResp
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'realname'
     */
    @Test
    void realnameTest() {
        // TODO: test realname
    }

    /**
     * Test the property 'comment'
     */
    @Test
    void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'username'
     */
    @Test
    void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'sysadminFlag'
     */
    @Test
    void sysadminFlagTest() {
        // TODO: test sysadminFlag
    }

    /**
     * Test the property 'adminRoleInAuth'
     */
    @Test
    void adminRoleInAuthTest() {
        // TODO: test adminRoleInAuth
    }

    /**
     * Test the property 'oidcUserMeta'
     */
    @Test
    void oidcUserMetaTest() {
        // TODO: test oidcUserMeta
    }

    /**
     * Test the property 'creationTime'
     */
    @Test
    void creationTimeTest() {
        // TODO: test creationTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    void updateTimeTest() {
        // TODO: test updateTime
    }

}
