/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.WebhookTargetObject;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookPolicy
 */
class WebhookPolicyTest {
    private final WebhookPolicy model = new WebhookPolicy();

    /**
     * Model tests for WebhookPolicy
     */
    @Test
    void testWebhookPolicy() {
        // TODO: test WebhookPolicy
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'targets'
     */
    @Test
    void targetsTest() {
        // TODO: test targets
    }

    /**
     * Test the property 'eventTypes'
     */
    @Test
    void eventTypesTest() {
        // TODO: test eventTypes
    }

    /**
     * Test the property 'creator'
     */
    @Test
    void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'creationTime'
     */
    @Test
    void creationTimeTest() {
        // TODO: test creationTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    void enabledTest() {
        // TODO: test enabled
    }

}
