/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookJob
 */
class WebhookJobTest {
    private final WebhookJob model = new WebhookJob();

    /**
     * Model tests for WebhookJob
     */
    @Test
    void testWebhookJob() {
        // TODO: test WebhookJob
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'policyId'
     */
    @Test
    void policyIdTest() {
        // TODO: test policyId
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'notifyType'
     */
    @Test
    void notifyTypeTest() {
        // TODO: test notifyType
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'jobDetail'
     */
    @Test
    void jobDetailTest() {
        // TODO: test jobDetail
    }

    /**
     * Test the property 'creationTime'
     */
    @Test
    void creationTimeTest() {
        // TODO: test creationTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    void updateTimeTest() {
        // TODO: test updateTime
    }

}
