/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Worker
 */
class WorkerTest {
    private final Worker model = new Worker();

    /**
     * Model tests for Worker
     */
    @Test
    void testWorker() {
        // TODO: test Worker
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'poolId'
     */
    @Test
    void poolIdTest() {
        // TODO: test poolId
    }

    /**
     * Test the property 'jobName'
     */
    @Test
    void jobNameTest() {
        // TODO: test jobName
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'checkIn'
     */
    @Test
    void checkInTest() {
        // TODO: test checkIn
    }

    /**
     * Test the property 'checkinAt'
     */
    @Test
    void checkinAtTest() {
        // TODO: test checkinAt
    }

}
