/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Configurations;
import com.ryan.openapi.harbor.client.model.ConfigurationsResponse;
import com.ryan.openapi.harbor.client.model.InternalConfigurationValue;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ConfigureApi
 */
@Disabled
public class ConfigureApiTest {

    private final ConfigureApi api = new ConfigureApi();

    
    /**
     * Get system configurations.
     *
     * This endpoint is for retrieving system configurations that only provides for admin user. 
     */
    @Test
    public void getConfigurationsTest()  {
        String xRequestId = null;
        ConfigurationsResponse response = api.getConfigurations(xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get internal configurations.
     *
     * This endpoint is for retrieving system configurations that only provides for internal api call. 
     */
    @Test
    public void getInternalconfigTest()  {
        String xRequestId = null;
        Map<String, InternalConfigurationValue> response = api.getInternalconfig(xRequestId);

        // TODO: test validations
    }
    
    /**
     * Modify system configurations.
     *
     * This endpoint is for modifying system configurations that only provides for admin user. 
     */
    @Test
    public void updateConfigurationsTest()  {
        Configurations configurations = null;
        String xRequestId = null;
        api.updateConfigurations(configurations, xRequestId);

        // TODO: test validations
    }
    
}