/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.ActionRequest;
import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.JobQueue;
import com.ryan.openapi.harbor.client.model.Worker;
import com.ryan.openapi.harbor.client.model.WorkerPool;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for JobserviceApi
 */
@Disabled
public class JobserviceApiTest {

    private final JobserviceApi api = new JobserviceApi();

    
    /**
     * Get job log by job id
     *
     * Get job log by job id, it is only used by administrator
     */
    @Test
    public void actionGetJobLogTest()  {
        String jobId = null;
        String xRequestId = null;
        String response = api.actionGetJobLog(jobId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * stop and clean, pause, resume pending jobs in the queue
     *
     * stop and clean, pause, resume pending jobs in the queue
     */
    @Test
    public void actionPendingJobsTest()  {
        String jobType = null;
        ActionRequest actionRequest = null;
        String xRequestId = null;
        api.actionPendingJobs(jobType, actionRequest, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get worker pools
     *
     * Get worker pools
     */
    @Test
    public void getWorkerPoolsTest()  {
        String xRequestId = null;
        List<WorkerPool> response = api.getWorkerPools(xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get workers
     *
     * Get workers in current pool
     */
    @Test
    public void getWorkersTest()  {
        String poolId = null;
        String xRequestId = null;
        List<Worker> response = api.getWorkers(poolId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * list job queues
     *
     * list job queue
     */
    @Test
    public void listJobQueuesTest()  {
        String xRequestId = null;
        List<JobQueue> response = api.listJobQueues(xRequestId);

        // TODO: test validations
    }
    
    /**
     * Stop running job
     *
     * Stop running job
     */
    @Test
    public void stopRunningJobTest()  {
        String jobId = null;
        String xRequestId = null;
        api.stopRunningJob(jobId, xRequestId);

        // TODO: test validations
    }
    
}