/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.Label;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for LabelApi
 */
@Disabled
public class LabelApiTest {

    private final LabelApi api = new LabelApi();

    
    /**
     * Post creates a label
     *
     * This endpoint let user creates a label. 
     */
    @Test
    public void createLabelTest()  {
        Label label = null;
        String xRequestId = null;
        api.createLabel(label, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Delete the label specified by ID.
     *
     * Delete the label specified by ID. 
     */
    @Test
    public void deleteLabelTest()  {
        Long labelId = null;
        String xRequestId = null;
        api.deleteLabel(labelId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get the label specified by ID.
     *
     * This endpoint let user get the label by specific ID. 
     */
    @Test
    public void getLabelByIDTest()  {
        Long labelId = null;
        String xRequestId = null;
        Label response = api.getLabelByID(labelId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * List labels according to the query strings.
     *
     * This endpoint let user list labels by name, scope and project_id 
     */
    @Test
    public void listLabelsTest()  {
        String xRequestId = null;
        String q = null;
        String sort = null;
        Long page = null;
        Long pageSize = null;
        String name = null;
        String scope = null;
        Long projectId = null;
        List<Label> response = api.listLabels(xRequestId, q, sort, page, pageSize, name, scope, projectId);

        // TODO: test validations
    }
    
    /**
     * Update the label properties.
     *
     * This endpoint let user update label properties. 
     */
    @Test
    public void updateLabelTest()  {
        Long labelId = null;
        Label label = null;
        String xRequestId = null;
        api.updateLabel(labelId, label, xRequestId);

        // TODO: test validations
    }
    
}