/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.PingOIDCRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for OidcApi
 */
@Disabled
public class OidcApiTest {

    private final OidcApi api = new OidcApi();

    
    /**
     * Test the OIDC endpoint.
     *
     * Test the OIDC endpoint, the setting of the endpoint is provided in the request.  This API can only be called by system admin. 
     */
    @Test
    public void pingOIDCTest()  {
        PingOIDCRequest endpoint = null;
        String xRequestId = null;
        api.pingOIDC(endpoint, xRequestId);

        // TODO: test validations
    }
    
}