/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for PingApi
 */
@Disabled
public class PingApiTest {

    private final PingApi api = new PingApi();

    
    /**
     * Ping Harbor to check if the API server is alive.
     *
     * This API simply replies a pong to indicate the process to handle API is up, disregarding the health status of dependent components. This path does not require any authentication.
     */
    @Test
    public void getPingTest()  {
        String xRequestId = null;
        String response = api.getPing(xRequestId);

        // TODO: test validations
    }
    
}