/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Artifact;
import com.ryan.openapi.harbor.client.model.AuditLog;
import com.ryan.openapi.harbor.client.model.AuditLogExt;
import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.Project;
import com.ryan.openapi.harbor.client.model.ProjectDeletable;
import com.ryan.openapi.harbor.client.model.ProjectReq;
import com.ryan.openapi.harbor.client.model.ProjectScanner;
import com.ryan.openapi.harbor.client.model.ProjectSummary;
import com.ryan.openapi.harbor.client.model.ScannerRegistration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ProjectApi
 */
@Disabled
public class ProjectApiTest {

    private final ProjectApi api = new ProjectApi();

    
    /**
     * Create a new project.
     *
     * This endpoint is for user to create a new project.
     */
    @Test
    public void createProjectTest()  {
        ProjectReq project = null;
        String xRequestId = null;
        Boolean xResourceNameInLocation = null;
        api.createProject(project, xRequestId, xResourceNameInLocation);

        // TODO: test validations
    }
    
    /**
     * Delete project by projectID
     *
     * This endpoint is aimed to delete project by project ID.
     */
    @Test
    public void deleteProjectTest()  {
        String projectNameOrId = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        api.deleteProject(projectNameOrId, xRequestId, xIsResourceName);

        // TODO: test validations
    }
    
    /**
     * Get recent logs of the projects
     *
     * Get recent logs of the projects
     */
    @Test
    public void getLogExtsTest()  {
        String projectName = null;
        String xRequestId = null;
        String q = null;
        String sort = null;
        Long page = null;
        Long pageSize = null;
        List<AuditLogExt> response = api.getLogExts(projectName, xRequestId, q, sort, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Get recent logs of the projects (deprecated)
     *
     * Get recent logs of the projects, it only query the previous version&#39;s audit log
     */
    @Test
    public void getLogsTest()  {
        String projectName = null;
        String xRequestId = null;
        String q = null;
        String sort = null;
        Long page = null;
        Long pageSize = null;
        List<AuditLog> response = api.getLogs(projectName, xRequestId, q, sort, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Return specific project detail information
     *
     * This endpoint returns specific project information by project ID.
     */
    @Test
    public void getProjectTest()  {
        String projectNameOrId = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        Project response = api.getProject(projectNameOrId, xRequestId, xIsResourceName);

        // TODO: test validations
    }
    
    /**
     * Get the deletable status of the project
     *
     * Get the deletable status of the project
     */
    @Test
    public void getProjectDeletableTest()  {
        String projectNameOrId = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        ProjectDeletable response = api.getProjectDeletable(projectNameOrId, xRequestId, xIsResourceName);

        // TODO: test validations
    }
    
    /**
     * Get summary of the project.
     *
     * Get summary of the project.
     */
    @Test
    public void getProjectSummaryTest()  {
        String projectNameOrId = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        ProjectSummary response = api.getProjectSummary(projectNameOrId, xRequestId, xIsResourceName);

        // TODO: test validations
    }
    
    /**
     * Get project level scanner
     *
     * Get the scanner registration of the specified project. If no scanner registration is configured for the specified project, the system default scanner registration will be returned.
     */
    @Test
    public void getScannerOfProjectTest()  {
        String projectNameOrId = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        ScannerRegistration response = api.getScannerOfProject(projectNameOrId, xRequestId, xIsResourceName);

        // TODO: test validations
    }
    
    /**
     * Check if the project name user provided already exists.
     *
     * This endpoint is used to check if the project name provided already exist.
     */
    @Test
    public void headProjectTest()  {
        String projectName = null;
        String xRequestId = null;
        api.headProject(projectName, xRequestId);

        // TODO: test validations
    }
    
    /**
     * List artifacts
     *
     * List artifacts of the specified project
     */
    @Test
    public void listArtifactsOfProjectTest()  {
        String projectNameOrId = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        String q = null;
        String sort = null;
        Long page = null;
        Long pageSize = null;
        String xAcceptVulnerabilities = null;
        Boolean withTag = null;
        Boolean withLabel = null;
        Boolean withScanOverview = null;
        Boolean withSbomOverview = null;
        Boolean withImmutableStatus = null;
        Boolean withAccessory = null;
        Boolean latestInRepository = null;
        List<Artifact> response = api.listArtifactsOfProject(projectNameOrId, xRequestId, xIsResourceName, q, sort, page, pageSize, xAcceptVulnerabilities, withTag, withLabel, withScanOverview, withSbomOverview, withImmutableStatus, withAccessory, latestInRepository);

        // TODO: test validations
    }
    
    /**
     * List projects
     *
     * This endpoint returns projects created by Harbor.
     */
    @Test
    public void listProjectsTest()  {
        String xRequestId = null;
        String q = null;
        Long page = null;
        Long pageSize = null;
        String sort = null;
        String name = null;
        Boolean _public = null;
        String owner = null;
        Boolean withDetail = null;
        List<Project> response = api.listProjects(xRequestId, q, page, pageSize, sort, name, _public, owner, withDetail);

        // TODO: test validations
    }
    
    /**
     * Get scanner registration candidates for configurating project level scanner
     *
     * Retrieve the system configured scanner registrations as candidates of setting project level scanner.
     */
    @Test
    public void listScannerCandidatesOfProjectTest()  {
        String projectNameOrId = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        String q = null;
        String sort = null;
        Long page = null;
        Long pageSize = null;
        List<ScannerRegistration> response = api.listScannerCandidatesOfProject(projectNameOrId, xRequestId, xIsResourceName, q, sort, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Configure scanner for the specified project
     *
     * Set one of the system configured scanner registration as the indepndent scanner of the specified project.
     */
    @Test
    public void setScannerOfProjectTest()  {
        String projectNameOrId = null;
        ProjectScanner payload = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        api.setScannerOfProject(projectNameOrId, payload, xRequestId, xIsResourceName);

        // TODO: test validations
    }
    
    /**
     * Update properties for a selected project.
     *
     * This endpoint is aimed to update the properties of a project.
     */
    @Test
    public void updateProjectTest()  {
        String projectNameOrId = null;
        ProjectReq project = null;
        String xRequestId = null;
        Boolean xIsResourceName = null;
        api.updateProject(projectNameOrId, project, xRequestId, xIsResourceName);

        // TODO: test validations
    }
    
}