/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.Robot;
import com.ryan.openapi.harbor.client.model.RobotCreate;
import com.ryan.openapi.harbor.client.model.RobotCreated;
import com.ryan.openapi.harbor.client.model.RobotSec;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for RobotApi
 */
@Disabled
public class RobotApiTest {

    private final RobotApi api = new RobotApi();

    
    /**
     * Create a robot account
     *
     * Create a robot account
     */
    @Test
    public void createRobotTest()  {
        RobotCreate robot = null;
        String xRequestId = null;
        RobotCreated response = api.createRobot(robot, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Delete a robot account
     *
     * This endpoint deletes specific robot account information by robot ID.
     */
    @Test
    public void deleteRobotTest()  {
        Integer robotId = null;
        String xRequestId = null;
        api.deleteRobot(robotId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get a robot account
     *
     * This endpoint returns specific robot account information by robot ID.
     */
    @Test
    public void getRobotByIDTest()  {
        Integer robotId = null;
        String xRequestId = null;
        Robot response = api.getRobotByID(robotId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get robot account
     *
     * List the robot accounts with the specified level and project.
     */
    @Test
    public void listRobotTest()  {
        String xRequestId = null;
        String q = null;
        String sort = null;
        Long page = null;
        Long pageSize = null;
        List<Robot> response = api.listRobot(xRequestId, q, sort, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Refresh the robot secret
     *
     * Refresh the robot secret
     */
    @Test
    public void refreshSecTest()  {
        Integer robotId = null;
        RobotSec robotSec = null;
        String xRequestId = null;
        RobotSec response = api.refreshSec(robotId, robotSec, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Update a robot account
     *
     * This endpoint updates specific robot account information by robot ID.
     */
    @Test
    public void updateRobotTest()  {
        Integer robotId = null;
        Robot robot = null;
        String xRequestId = null;
        api.updateRobot(robotId, robot, xRequestId);

        // TODO: test validations
    }
    
}