/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.ScanType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ScanApi
 */
@Disabled
public class ScanApiTest {

    private final ScanApi api = new ScanApi();

    
    /**
     * Get the log of the scan report
     *
     * Get the log of the scan report
     */
    @Test
    public void getReportLogTest()  {
        String projectName = null;
        String repositoryName = null;
        String reference = null;
        String reportId = null;
        String xRequestId = null;
        String response = api.getReportLog(projectName, repositoryName, reference, reportId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Scan the artifact
     *
     * Scan the specified artifact
     */
    @Test
    public void scanArtifactTest()  {
        String projectName = null;
        String repositoryName = null;
        String reference = null;
        String xRequestId = null;
        ScanType scanType = null;
        api.scanArtifact(projectName, repositoryName, reference, xRequestId, scanType);

        // TODO: test validations
    }
    
    /**
     * Cancelling a scan job for a particular artifact
     *
     * Cancelling a scan job for a particular artifact
     */
    @Test
    public void stopScanArtifactTest()  {
        String projectName = null;
        String repositoryName = null;
        String reference = null;
        ScanType scanType = null;
        String xRequestId = null;
        api.stopScanArtifact(projectName, repositoryName, reference, scanType, xRequestId);

        // TODO: test validations
    }
    
}