/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.ScheduleTask;
import com.ryan.openapi.harbor.client.model.SchedulerStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ScheduleApi
 */
@Disabled
public class ScheduleApiTest {

    private final ScheduleApi api = new ScheduleApi();

    
    /**
     * 
     *
     * Get scheduler paused status
     */
    @Test
    public void getSchedulePausedTest()  {
        String jobType = null;
        String xRequestId = null;
        SchedulerStatus response = api.getSchedulePaused(jobType, xRequestId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * List schedules
     */
    @Test
    public void listSchedulesTest()  {
        String xRequestId = null;
        Long page = null;
        Long pageSize = null;
        List<ScheduleTask> response = api.listSchedules(xRequestId, page, pageSize);

        // TODO: test validations
    }
    
}