/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.Statistic;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for StatisticApi
 */
@Disabled
public class StatisticApiTest {

    private final StatisticApi api = new StatisticApi();

    
    /**
     * Get the statistic information about the projects and repositories
     *
     * Get the statistic information about the projects and repositories
     */
    @Test
    public void getStatisticTest()  {
        String xRequestId = null;
        Statistic response = api.getStatistic(xRequestId);

        // TODO: test validations
    }
    
}