/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.CVEAllowlist;
import com.ryan.openapi.harbor.client.model.Errors;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SystemCveAllowlistApi
 */
@Disabled
public class SystemCveAllowlistApiTest {

    private final SystemCveAllowlistApi api = new SystemCveAllowlistApi();

    
    /**
     * Get the system level allowlist of CVE.
     *
     * Get the system level allowlist of CVE.  This API can be called by all authenticated users.
     */
    @Test
    public void getSystemCVEAllowlistTest()  {
        String xRequestId = null;
        CVEAllowlist response = api.getSystemCVEAllowlist(xRequestId);

        // TODO: test validations
    }
    
    /**
     * Update the system level allowlist of CVE.
     *
     * This API overwrites the system level allowlist of CVE with the list in request body.  Only system Admin has permission to call this API.
     */
    @Test
    public void putSystemCVEAllowlistTest()  {
        String xRequestId = null;
        CVEAllowlist allowlist = null;
        api.putSystemCVEAllowlist(xRequestId, allowlist);

        // TODO: test validations
    }
    
}