/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.api;

import com.ryan.openapi.harbor.client.model.Errors;
import com.ryan.openapi.harbor.client.model.OIDCCliSecretReq;
import com.ryan.openapi.harbor.client.model.PasswordReq;
import com.ryan.openapi.harbor.client.model.Permission;
import com.ryan.openapi.harbor.client.model.UserCreationReq;
import com.ryan.openapi.harbor.client.model.UserProfile;
import com.ryan.openapi.harbor.client.model.UserResp;
import com.ryan.openapi.harbor.client.model.UserSearchRespItem;
import com.ryan.openapi.harbor.client.model.UserSysAdminFlag;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for UserApi
 */
@Disabled
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * Create a local user.
     *
     * This API can be used only when the authentication mode is for local DB.  When self registration is disabled.
     */
    @Test
    public void createUserTest()  {
        UserCreationReq userReq = null;
        String xRequestId = null;
        api.createUser(userReq, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Mark a registered user as be removed.
     *
     * This endpoint let administrator of Harbor mark a registered user as removed.It actually won&#39;t be deleted from DB. 
     */
    @Test
    public void deleteUserTest()  {
        Integer userId = null;
        String xRequestId = null;
        api.deleteUser(userId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get current user info.
     *
     * 
     */
    @Test
    public void getCurrentUserInfoTest()  {
        String xRequestId = null;
        UserResp response = api.getCurrentUserInfo(xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get current user permissions.
     *
     * 
     */
    @Test
    public void getCurrentUserPermissionsTest()  {
        String xRequestId = null;
        String scope = null;
        Boolean relative = null;
        List<Permission> response = api.getCurrentUserPermissions(xRequestId, scope, relative);

        // TODO: test validations
    }
    
    /**
     * Get a user&#39;s profile.
     *
     * 
     */
    @Test
    public void getUserTest()  {
        Integer userId = null;
        String xRequestId = null;
        UserResp response = api.getUser(userId, xRequestId);

        // TODO: test validations
    }
    
    /**
     * List users
     *
     * 
     */
    @Test
    public void listUsersTest()  {
        String xRequestId = null;
        String q = null;
        String sort = null;
        Long page = null;
        Long pageSize = null;
        List<UserResp> response = api.listUsers(xRequestId, q, sort, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Search users by username
     *
     * This endpoint is to search the users by username.  It&#39;s open for all authenticated requests. 
     */
    @Test
    public void searchUsersTest()  {
        String username = null;
        String xRequestId = null;
        Long page = null;
        Long pageSize = null;
        List<UserSearchRespItem> response = api.searchUsers(username, xRequestId, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Set CLI secret for a user.
     *
     * This endpoint let user generate a new CLI secret for himself.  This API only works when auth mode is set to &#39;OIDC&#39;. Once this API returns with successful status, the old secret will be invalid, as there will be only one CLI secret for a user.
     */
    @Test
    public void setCliSecretTest()  {
        Integer userId = null;
        OIDCCliSecretReq secret = null;
        String xRequestId = null;
        api.setCliSecret(userId, secret, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Update a registered user to change to be an administrator of Harbor.
     *
     * 
     */
    @Test
    public void setUserSysAdminTest()  {
        Integer userId = null;
        UserSysAdminFlag sysadminFlag = null;
        String xRequestId = null;
        api.setUserSysAdmin(userId, sysadminFlag, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Change the password on a user that already exists.
     *
     * This endpoint is for user to update password. Users with the admin role can change any user&#39;s password. Regular users can change only their own password. 
     */
    @Test
    public void updateUserPasswordTest()  {
        Integer userId = null;
        PasswordReq password = null;
        String xRequestId = null;
        api.updateUserPassword(userId, password, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Update user&#39;s profile.
     *
     * 
     */
    @Test
    public void updateUserProfileTest()  {
        Integer userId = null;
        UserProfile profile = null;
        String xRequestId = null;
        api.updateUserProfile(userId, profile, xRequestId);

        // TODO: test validations
    }
    
}