/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The accessory of the artifact
 */
@JsonPropertyOrder({
  Accessory.JSON_PROPERTY_ID,
  Accessory.JSON_PROPERTY_ARTIFACT_ID,
  Accessory.JSON_PROPERTY_SUBJECT_ARTIFACT_ID,
  Accessory.JSON_PROPERTY_SUBJECT_ARTIFACT_DIGEST,
  Accessory.JSON_PROPERTY_SUBJECT_ARTIFACT_REPO,
  Accessory.JSON_PROPERTY_SIZE,
  Accessory.JSON_PROPERTY_DIGEST,
  Accessory.JSON_PROPERTY_TYPE,
  Accessory.JSON_PROPERTY_ICON,
  Accessory.JSON_PROPERTY_CREATION_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Accessory {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_ARTIFACT_ID = "artifact_id";
  @jakarta.annotation.Nullable
  private Long artifactId;

  public static final String JSON_PROPERTY_SUBJECT_ARTIFACT_ID = "subject_artifact_id";
  @jakarta.annotation.Nullable
  private Long subjectArtifactId;

  public static final String JSON_PROPERTY_SUBJECT_ARTIFACT_DIGEST = "subject_artifact_digest";
  @jakarta.annotation.Nullable
  private String subjectArtifactDigest;

  public static final String JSON_PROPERTY_SUBJECT_ARTIFACT_REPO = "subject_artifact_repo";
  @jakarta.annotation.Nullable
  private String subjectArtifactRepo;

  public static final String JSON_PROPERTY_SIZE = "size";
  @jakarta.annotation.Nullable
  private Long size;

  public static final String JSON_PROPERTY_DIGEST = "digest";
  @jakarta.annotation.Nullable
  private String digest;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_ICON = "icon";
  @jakarta.annotation.Nullable
  private String icon;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @jakarta.annotation.Nullable
  private Date creationTime;

  public Accessory() {
  }

  public Accessory id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The ID of the accessory
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public Accessory artifactId(@jakarta.annotation.Nullable Long artifactId) {
    
    this.artifactId = artifactId;
    return this;
  }

  /**
   * The artifact id of the accessory
   * @return artifactId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getArtifactId() {
    return artifactId;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArtifactId(@jakarta.annotation.Nullable Long artifactId) {
    this.artifactId = artifactId;
  }

  public Accessory subjectArtifactId(@jakarta.annotation.Nullable Long subjectArtifactId) {
    
    this.subjectArtifactId = subjectArtifactId;
    return this;
  }

  /**
   * Going to be deprecated, use repo and digest for insteand. The subject artifact id of the accessory.
   * @return subjectArtifactId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSubjectArtifactId() {
    return subjectArtifactId;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectArtifactId(@jakarta.annotation.Nullable Long subjectArtifactId) {
    this.subjectArtifactId = subjectArtifactId;
  }

  public Accessory subjectArtifactDigest(@jakarta.annotation.Nullable String subjectArtifactDigest) {
    
    this.subjectArtifactDigest = subjectArtifactDigest;
    return this;
  }

  /**
   * The subject artifact digest of the accessory
   * @return subjectArtifactDigest
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ARTIFACT_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubjectArtifactDigest() {
    return subjectArtifactDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ARTIFACT_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectArtifactDigest(@jakarta.annotation.Nullable String subjectArtifactDigest) {
    this.subjectArtifactDigest = subjectArtifactDigest;
  }

  public Accessory subjectArtifactRepo(@jakarta.annotation.Nullable String subjectArtifactRepo) {
    
    this.subjectArtifactRepo = subjectArtifactRepo;
    return this;
  }

  /**
   * The subject artifact repository name of the accessory
   * @return subjectArtifactRepo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ARTIFACT_REPO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubjectArtifactRepo() {
    return subjectArtifactRepo;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ARTIFACT_REPO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectArtifactRepo(@jakarta.annotation.Nullable String subjectArtifactRepo) {
    this.subjectArtifactRepo = subjectArtifactRepo;
  }

  public Accessory size(@jakarta.annotation.Nullable Long size) {
    
    this.size = size;
    return this;
  }

  /**
   * The artifact size of the accessory
   * @return size
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSize() {
    return size;
  }


  @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(@jakarta.annotation.Nullable Long size) {
    this.size = size;
  }

  public Accessory digest(@jakarta.annotation.Nullable String digest) {
    
    this.digest = digest;
    return this;
  }

  /**
   * The artifact digest of the accessory
   * @return digest
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDigest() {
    return digest;
  }


  @JsonProperty(value = JSON_PROPERTY_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigest(@jakarta.annotation.Nullable String digest) {
    this.digest = digest;
  }

  public Accessory type(@jakarta.annotation.Nullable String type) {
    
    this.type = type;
    return this;
  }

  /**
   * The artifact size of the accessory
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }

  public Accessory icon(@jakarta.annotation.Nullable String icon) {
    
    this.icon = icon;
    return this;
  }

  /**
   * The icon of the accessory
   * @return icon
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIcon() {
    return icon;
  }


  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIcon(@jakarta.annotation.Nullable String icon) {
    this.icon = icon;
  }

  public Accessory creationTime(@jakarta.annotation.Nullable Date creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

  /**
   * The creation time of the accessory
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Date creationTime) {
    this.creationTime = creationTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Accessory accessory = (Accessory) o;
    return Objects.equals(this.id, accessory.id) &&
        Objects.equals(this.artifactId, accessory.artifactId) &&
        Objects.equals(this.subjectArtifactId, accessory.subjectArtifactId) &&
        Objects.equals(this.subjectArtifactDigest, accessory.subjectArtifactDigest) &&
        Objects.equals(this.subjectArtifactRepo, accessory.subjectArtifactRepo) &&
        Objects.equals(this.size, accessory.size) &&
        Objects.equals(this.digest, accessory.digest) &&
        Objects.equals(this.type, accessory.type) &&
        Objects.equals(this.icon, accessory.icon) &&
        Objects.equals(this.creationTime, accessory.creationTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, artifactId, subjectArtifactId, subjectArtifactDigest, subjectArtifactRepo, size, digest, type, icon, creationTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Accessory {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    artifactId: ").append(toIndentedString(artifactId)).append("\n");
    sb.append("    subjectArtifactId: ").append(toIndentedString(subjectArtifactId)).append("\n");
    sb.append("    subjectArtifactDigest: ").append(toIndentedString(subjectArtifactDigest)).append("\n");
    sb.append("    subjectArtifactRepo: ").append(toIndentedString(subjectArtifactRepo)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Accessory instance;

    public Builder() {
      this(new Accessory());
    }

    protected Builder(Accessory instance) {
      this.instance = instance;
    }

    public Accessory.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public Accessory.Builder artifactId(Long artifactId) {
      this.instance.artifactId = artifactId;
      return this;
    }
    public Accessory.Builder subjectArtifactId(Long subjectArtifactId) {
      this.instance.subjectArtifactId = subjectArtifactId;
      return this;
    }
    public Accessory.Builder subjectArtifactDigest(String subjectArtifactDigest) {
      this.instance.subjectArtifactDigest = subjectArtifactDigest;
      return this;
    }
    public Accessory.Builder subjectArtifactRepo(String subjectArtifactRepo) {
      this.instance.subjectArtifactRepo = subjectArtifactRepo;
      return this;
    }
    public Accessory.Builder size(Long size) {
      this.instance.size = size;
      return this;
    }
    public Accessory.Builder digest(String digest) {
      this.instance.digest = digest;
      return this;
    }
    public Accessory.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public Accessory.Builder icon(String icon) {
      this.instance.icon = icon;
      return this;
    }
    public Accessory.Builder creationTime(Date creationTime) {
      this.instance.creationTime = creationTime;
      return this;
    }


    /**
    * returns a built Accessory instance.
    *
    * The builder is not reusable.
    */
    public Accessory build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Accessory.Builder builder() {
    return new Accessory.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Accessory.Builder toBuilder() {
    return new Accessory.Builder()
      .id(getId())
      .artifactId(getArtifactId())
      .subjectArtifactId(getSubjectArtifactId())
      .subjectArtifactDigest(getSubjectArtifactDigest())
      .subjectArtifactRepo(getSubjectArtifactRepo())
      .size(getSize())
      .digest(getDigest())
      .type(getType())
      .icon(getIcon())
      .creationTime(getCreationTime());
  }


}

