/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Access
 */
@JsonPropertyOrder({
  Access.JSON_PROPERTY_RESOURCE,
  Access.JSON_PROPERTY_ACTION,
  Access.JSON_PROPERTY_EFFECT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Access {
  public static final String JSON_PROPERTY_RESOURCE = "resource";
  @jakarta.annotation.Nullable
  private String resource;

  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nullable
  private String action;

  public static final String JSON_PROPERTY_EFFECT = "effect";
  @jakarta.annotation.Nullable
  private String effect;

  public Access() {
  }

  public Access resource(@jakarta.annotation.Nullable String resource) {
    
    this.resource = resource;
    return this;
  }

  /**
   * The resource of the access. Possible resources are listed here for system and project level https://github.com/goharbor/harbor/blob/main/src/common/rbac/const.go
   * @return resource
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResource() {
    return resource;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResource(@jakarta.annotation.Nullable String resource) {
    this.resource = resource;
  }

  public Access action(@jakarta.annotation.Nullable String action) {
    
    this.action = action;
    return this;
  }

  /**
   * The action of the access. Possible actions are *, pull, push, create, read, update, delete, list, operate, scanner-pull and stop.
   * @return action
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(@jakarta.annotation.Nullable String action) {
    this.action = action;
  }

  public Access effect(@jakarta.annotation.Nullable String effect) {
    
    this.effect = effect;
    return this;
  }

  /**
   * The effect of the access
   * @return effect
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EFFECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEffect() {
    return effect;
  }


  @JsonProperty(value = JSON_PROPERTY_EFFECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffect(@jakarta.annotation.Nullable String effect) {
    this.effect = effect;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Access access = (Access) o;
    return Objects.equals(this.resource, access.resource) &&
        Objects.equals(this.action, access.action) &&
        Objects.equals(this.effect, access.effect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource, action, effect);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Access {\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    effect: ").append(toIndentedString(effect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Access instance;

    public Builder() {
      this(new Access());
    }

    protected Builder(Access instance) {
      this.instance = instance;
    }

    public Access.Builder resource(String resource) {
      this.instance.resource = resource;
      return this;
    }
    public Access.Builder action(String action) {
      this.instance.action = action;
      return this;
    }
    public Access.Builder effect(String effect) {
      this.instance.effect = effect;
      return this;
    }


    /**
    * returns a built Access instance.
    *
    * The builder is not reusable.
    */
    public Access build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Access.Builder builder() {
    return new Access.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Access.Builder toBuilder() {
    return new Access.Builder()
      .resource(getResource())
      .action(getAction())
      .effect(getEffect());
  }


}

