/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ImmutableSelector
 */
@JsonPropertyOrder({
  ImmutableSelector.JSON_PROPERTY_KIND,
  ImmutableSelector.JSON_PROPERTY_DECORATION,
  ImmutableSelector.JSON_PROPERTY_PATTERN,
  ImmutableSelector.JSON_PROPERTY_EXTRAS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ImmutableSelector {
  public static final String JSON_PROPERTY_KIND = "kind";
  @jakarta.annotation.Nullable
  private String kind;

  public static final String JSON_PROPERTY_DECORATION = "decoration";
  @jakarta.annotation.Nullable
  private String decoration;

  public static final String JSON_PROPERTY_PATTERN = "pattern";
  @jakarta.annotation.Nullable
  private String pattern;

  public static final String JSON_PROPERTY_EXTRAS = "extras";
  @jakarta.annotation.Nullable
  private String extras;

  public ImmutableSelector() {
  }

  public ImmutableSelector kind(@jakarta.annotation.Nullable String kind) {
    
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@jakarta.annotation.Nullable String kind) {
    this.kind = kind;
  }

  public ImmutableSelector decoration(@jakarta.annotation.Nullable String decoration) {
    
    this.decoration = decoration;
    return this;
  }

  /**
   * Get decoration
   * @return decoration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DECORATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDecoration() {
    return decoration;
  }


  @JsonProperty(value = JSON_PROPERTY_DECORATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDecoration(@jakarta.annotation.Nullable String decoration) {
    this.decoration = decoration;
  }

  public ImmutableSelector pattern(@jakarta.annotation.Nullable String pattern) {
    
    this.pattern = pattern;
    return this;
  }

  /**
   * Get pattern
   * @return pattern
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPattern() {
    return pattern;
  }


  @JsonProperty(value = JSON_PROPERTY_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPattern(@jakarta.annotation.Nullable String pattern) {
    this.pattern = pattern;
  }

  public ImmutableSelector extras(@jakarta.annotation.Nullable String extras) {
    
    this.extras = extras;
    return this;
  }

  /**
   * Get extras
   * @return extras
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTRAS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtras() {
    return extras;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTRAS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtras(@jakarta.annotation.Nullable String extras) {
    this.extras = extras;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImmutableSelector immutableSelector = (ImmutableSelector) o;
    return Objects.equals(this.kind, immutableSelector.kind) &&
        Objects.equals(this.decoration, immutableSelector.decoration) &&
        Objects.equals(this.pattern, immutableSelector.pattern) &&
        Objects.equals(this.extras, immutableSelector.extras);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, decoration, pattern, extras);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImmutableSelector {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    decoration: ").append(toIndentedString(decoration)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    extras: ").append(toIndentedString(extras)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ImmutableSelector instance;

    public Builder() {
      this(new ImmutableSelector());
    }

    protected Builder(ImmutableSelector instance) {
      this.instance = instance;
    }

    public ImmutableSelector.Builder kind(String kind) {
      this.instance.kind = kind;
      return this;
    }
    public ImmutableSelector.Builder decoration(String decoration) {
      this.instance.decoration = decoration;
      return this;
    }
    public ImmutableSelector.Builder pattern(String pattern) {
      this.instance.pattern = pattern;
      return this;
    }
    public ImmutableSelector.Builder extras(String extras) {
      this.instance.extras = extras;
      return this;
    }


    /**
    * returns a built ImmutableSelector instance.
    *
    * The builder is not reusable.
    */
    public ImmutableSelector build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ImmutableSelector.Builder builder() {
    return new ImmutableSelector.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ImmutableSelector.Builder toBuilder() {
    return new ImmutableSelector.Builder()
      .kind(getKind())
      .decoration(getDecoration())
      .pattern(getPattern())
      .extras(getExtras());
  }


}

