/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Instance
 */
@JsonPropertyOrder({
  Instance.JSON_PROPERTY_ID,
  Instance.JSON_PROPERTY_NAME,
  Instance.JSON_PROPERTY_DESCRIPTION,
  Instance.JSON_PROPERTY_VENDOR,
  Instance.JSON_PROPERTY_ENDPOINT,
  Instance.JSON_PROPERTY_AUTH_MODE,
  Instance.JSON_PROPERTY_AUTH_INFO,
  Instance.JSON_PROPERTY_STATUS,
  Instance.JSON_PROPERTY_ENABLED,
  Instance.JSON_PROPERTY_DEFAULT,
  Instance.JSON_PROPERTY_INSECURE,
  Instance.JSON_PROPERTY_SETUP_TIMESTAMP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Instance {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_VENDOR = "vendor";
  @jakarta.annotation.Nullable
  private String vendor;

  public static final String JSON_PROPERTY_ENDPOINT = "endpoint";
  @jakarta.annotation.Nullable
  private String endpoint;

  public static final String JSON_PROPERTY_AUTH_MODE = "auth_mode";
  @jakarta.annotation.Nullable
  private String authMode;

  public static final String JSON_PROPERTY_AUTH_INFO = "auth_info";
  @jakarta.annotation.Nullable
  private Map<String, String> authInfo = new HashMap<>();

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_DEFAULT = "default";
  @jakarta.annotation.Nullable
  private Boolean _default;

  public static final String JSON_PROPERTY_INSECURE = "insecure";
  @jakarta.annotation.Nullable
  private Boolean insecure;

  public static final String JSON_PROPERTY_SETUP_TIMESTAMP = "setup_timestamp";
  @jakarta.annotation.Nullable
  private Long setupTimestamp;

  public Instance() {
  }

  public Instance id(@jakarta.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }

  public Instance name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Instance name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Instance description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Description of instance
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public Instance vendor(@jakarta.annotation.Nullable String vendor) {
    
    this.vendor = vendor;
    return this;
  }

  /**
   * Based on which driver, identified by ID
   * @return vendor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VENDOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVendor() {
    return vendor;
  }


  @JsonProperty(value = JSON_PROPERTY_VENDOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVendor(@jakarta.annotation.Nullable String vendor) {
    this.vendor = vendor;
  }

  public Instance endpoint(@jakarta.annotation.Nullable String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

  /**
   * The service endpoint of this instance
   * @return endpoint
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndpoint() {
    return endpoint;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoint(@jakarta.annotation.Nullable String endpoint) {
    this.endpoint = endpoint;
  }

  public Instance authMode(@jakarta.annotation.Nullable String authMode) {
    
    this.authMode = authMode;
    return this;
  }

  /**
   * The authentication way supported
   * @return authMode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthMode() {
    return authMode;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthMode(@jakarta.annotation.Nullable String authMode) {
    this.authMode = authMode;
  }

  public Instance authInfo(@jakarta.annotation.Nullable Map<String, String> authInfo) {
    
    this.authInfo = authInfo;
    return this;
  }

  public Instance putAuthInfoItem(String key, String authInfoItem) {
    if (this.authInfo == null) {
      this.authInfo = new HashMap<>();
    }
    this.authInfo.put(key, authInfoItem);
    return this;
  }

  /**
   * The auth credential data if exists
   * @return authInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getAuthInfo() {
    return authInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthInfo(@jakarta.annotation.Nullable Map<String, String> authInfo) {
    this.authInfo = authInfo;
  }

  public Instance status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * The health status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }

  public Instance enabled(@jakarta.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Whether the instance is activated or not
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public Instance _default(@jakarta.annotation.Nullable Boolean _default) {
    
    this._default = _default;
    return this;
  }

  /**
   * Whether the instance is default or not
   * @return _default
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDefault() {
    return _default;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefault(@jakarta.annotation.Nullable Boolean _default) {
    this._default = _default;
  }

  public Instance insecure(@jakarta.annotation.Nullable Boolean insecure) {
    
    this.insecure = insecure;
    return this;
  }

  /**
   * Whether the instance endpoint is insecure or not
   * @return insecure
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSECURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInsecure() {
    return insecure;
  }


  @JsonProperty(value = JSON_PROPERTY_INSECURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInsecure(@jakarta.annotation.Nullable Boolean insecure) {
    this.insecure = insecure;
  }

  public Instance setupTimestamp(@jakarta.annotation.Nullable Long setupTimestamp) {
    
    this.setupTimestamp = setupTimestamp;
    return this;
  }

  /**
   * The timestamp of instance setting up
   * @return setupTimestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SETUP_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSetupTimestamp() {
    return setupTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_SETUP_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetupTimestamp(@jakarta.annotation.Nullable Long setupTimestamp) {
    this.setupTimestamp = setupTimestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Instance instance = (Instance) o;
    return Objects.equals(this.id, instance.id) &&
        Objects.equals(this.name, instance.name) &&
        Objects.equals(this.description, instance.description) &&
        Objects.equals(this.vendor, instance.vendor) &&
        Objects.equals(this.endpoint, instance.endpoint) &&
        Objects.equals(this.authMode, instance.authMode) &&
        Objects.equals(this.authInfo, instance.authInfo) &&
        Objects.equals(this.status, instance.status) &&
        Objects.equals(this.enabled, instance.enabled) &&
        Objects.equals(this._default, instance._default) &&
        Objects.equals(this.insecure, instance.insecure) &&
        Objects.equals(this.setupTimestamp, instance.setupTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, vendor, endpoint, authMode, authInfo, status, enabled, _default, insecure, setupTimestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Instance {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    authMode: ").append(toIndentedString(authMode)).append("\n");
    sb.append("    authInfo: ").append(toIndentedString(authInfo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    insecure: ").append(toIndentedString(insecure)).append("\n");
    sb.append("    setupTimestamp: ").append(toIndentedString(setupTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Instance instance;

    public Builder() {
      this(new Instance());
    }

    protected Builder(Instance instance) {
      this.instance = instance;
    }

    public Instance.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public Instance.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public Instance.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public Instance.Builder vendor(String vendor) {
      this.instance.vendor = vendor;
      return this;
    }
    public Instance.Builder endpoint(String endpoint) {
      this.instance.endpoint = endpoint;
      return this;
    }
    public Instance.Builder authMode(String authMode) {
      this.instance.authMode = authMode;
      return this;
    }
    public Instance.Builder authInfo(Map<String, String> authInfo) {
      this.instance.authInfo = authInfo;
      return this;
    }
    public Instance.Builder status(String status) {
      this.instance.status = status;
      return this;
    }
    public Instance.Builder enabled(Boolean enabled) {
      this.instance.enabled = enabled;
      return this;
    }
    public Instance.Builder _default(Boolean _default) {
      this.instance._default = _default;
      return this;
    }
    public Instance.Builder insecure(Boolean insecure) {
      this.instance.insecure = insecure;
      return this;
    }
    public Instance.Builder setupTimestamp(Long setupTimestamp) {
      this.instance.setupTimestamp = setupTimestamp;
      return this;
    }


    /**
    * returns a built Instance instance.
    *
    * The builder is not reusable.
    */
    public Instance build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Instance.Builder builder() {
    return new Instance.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Instance.Builder toBuilder() {
    return new Instance.Builder()
      .id(getId())
      .name(getName())
      .description(getDescription())
      .vendor(getVendor())
      .endpoint(getEndpoint())
      .authMode(getAuthMode())
      .authInfo(getAuthInfo())
      .status(getStatus())
      .enabled(getEnabled())
      ._default(getDefault())
      .insecure(getInsecure())
      .setupTimestamp(getSetupTimestamp());
  }


}

