/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * the job queue info
 */
@JsonPropertyOrder({
  JobQueue.JSON_PROPERTY_JOB_TYPE,
  JobQueue.JSON_PROPERTY_COUNT,
  JobQueue.JSON_PROPERTY_LATENCY,
  JobQueue.JSON_PROPERTY_PAUSED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class JobQueue {
  public static final String JSON_PROPERTY_JOB_TYPE = "job_type";
  @jakarta.annotation.Nullable
  private String jobType;

  public static final String JSON_PROPERTY_COUNT = "count";
  @jakarta.annotation.Nullable
  private Integer count;

  public static final String JSON_PROPERTY_LATENCY = "latency";
  @jakarta.annotation.Nullable
  private Integer latency;

  public static final String JSON_PROPERTY_PAUSED = "paused";
  @jakarta.annotation.Nullable
  private Boolean paused;

  public JobQueue() {
  }

  public JobQueue jobType(@jakarta.annotation.Nullable String jobType) {
    
    this.jobType = jobType;
    return this;
  }

  /**
   * The type of the job queue
   * @return jobType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_JOB_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobType() {
    return jobType;
  }


  @JsonProperty(value = JSON_PROPERTY_JOB_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobType(@jakarta.annotation.Nullable String jobType) {
    this.jobType = jobType;
  }

  public JobQueue count(@jakarta.annotation.Nullable Integer count) {
    
    this.count = count;
    return this;
  }

  /**
   * The count of jobs in the job queue
   * @return count
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCount() {
    return count;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCount(@jakarta.annotation.Nullable Integer count) {
    this.count = count;
  }

  public JobQueue latency(@jakarta.annotation.Nullable Integer latency) {
    
    this.latency = latency;
    return this;
  }

  /**
   * The latency the job queue (seconds)
   * @return latency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLatency() {
    return latency;
  }


  @JsonProperty(value = JSON_PROPERTY_LATENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatency(@jakarta.annotation.Nullable Integer latency) {
    this.latency = latency;
  }

  public JobQueue paused(@jakarta.annotation.Nullable Boolean paused) {
    
    this.paused = paused;
    return this;
  }

  /**
   * The paused status of the job queue
   * @return paused
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAUSED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPaused() {
    return paused;
  }


  @JsonProperty(value = JSON_PROPERTY_PAUSED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaused(@jakarta.annotation.Nullable Boolean paused) {
    this.paused = paused;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobQueue jobQueue = (JobQueue) o;
    return Objects.equals(this.jobType, jobQueue.jobType) &&
        Objects.equals(this.count, jobQueue.count) &&
        Objects.equals(this.latency, jobQueue.latency) &&
        Objects.equals(this.paused, jobQueue.paused);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobType, count, latency, paused);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobQueue {\n");
    sb.append("    jobType: ").append(toIndentedString(jobType)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("    paused: ").append(toIndentedString(paused)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private JobQueue instance;

    public Builder() {
      this(new JobQueue());
    }

    protected Builder(JobQueue instance) {
      this.instance = instance;
    }

    public JobQueue.Builder jobType(String jobType) {
      this.instance.jobType = jobType;
      return this;
    }
    public JobQueue.Builder count(Integer count) {
      this.instance.count = count;
      return this;
    }
    public JobQueue.Builder latency(Integer latency) {
      this.instance.latency = latency;
      return this;
    }
    public JobQueue.Builder paused(Boolean paused) {
      this.instance.paused = paused;
      return this;
    }


    /**
    * returns a built JobQueue instance.
    *
    * The builder is not reusable.
    */
    public JobQueue build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static JobQueue.Builder builder() {
    return new JobQueue.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public JobQueue.Builder toBuilder() {
    return new JobQueue.Builder()
      .jobType(getJobType())
      .count(getCount())
      .latency(getLatency())
      .paused(getPaused());
  }


}

