/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Label
 */
@JsonPropertyOrder({
  Label.JSON_PROPERTY_ID,
  Label.JSON_PROPERTY_NAME,
  Label.JSON_PROPERTY_DESCRIPTION,
  Label.JSON_PROPERTY_COLOR,
  Label.JSON_PROPERTY_SCOPE,
  Label.JSON_PROPERTY_PROJECT_ID,
  Label.JSON_PROPERTY_CREATION_TIME,
  Label.JSON_PROPERTY_UPDATE_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Label {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_COLOR = "color";
  @jakarta.annotation.Nullable
  private String color;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @jakarta.annotation.Nullable
  private String scope;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private Long projectId;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @jakarta.annotation.Nullable
  private Date creationTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  @jakarta.annotation.Nullable
  private Date updateTime;

  public Label() {
  }

  public Label id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The ID of the label
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public Label name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name the label
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Label description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description the label
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public Label color(@jakarta.annotation.Nullable String color) {
    
    this.color = color;
    return this;
  }

  /**
   * The color the label
   * @return color
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getColor() {
    return color;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(@jakarta.annotation.Nullable String color) {
    this.color = color;
  }

  public Label scope(@jakarta.annotation.Nullable String scope) {
    
    this.scope = scope;
    return this;
  }

  /**
   * The scope the label
   * @return scope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@jakarta.annotation.Nullable String scope) {
    this.scope = scope;
  }

  public Label projectId(@jakarta.annotation.Nullable Long projectId) {
    
    this.projectId = projectId;
    return this;
  }

  /**
   * The ID of project that the label belongs to
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable Long projectId) {
    this.projectId = projectId;
  }

  public Label creationTime(@jakarta.annotation.Nullable Date creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

  /**
   * The creation time the label
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Date creationTime) {
    this.creationTime = creationTime;
  }

  public Label updateTime(@jakarta.annotation.Nullable Date updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

  /**
   * The update time of the label
   * @return updateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(@jakarta.annotation.Nullable Date updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Label label = (Label) o;
    return Objects.equals(this.id, label.id) &&
        Objects.equals(this.name, label.name) &&
        Objects.equals(this.description, label.description) &&
        Objects.equals(this.color, label.color) &&
        Objects.equals(this.scope, label.scope) &&
        Objects.equals(this.projectId, label.projectId) &&
        Objects.equals(this.creationTime, label.creationTime) &&
        Objects.equals(this.updateTime, label.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, color, scope, projectId, creationTime, updateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Label {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Label instance;

    public Builder() {
      this(new Label());
    }

    protected Builder(Label instance) {
      this.instance = instance;
    }

    public Label.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public Label.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public Label.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public Label.Builder color(String color) {
      this.instance.color = color;
      return this;
    }
    public Label.Builder scope(String scope) {
      this.instance.scope = scope;
      return this;
    }
    public Label.Builder projectId(Long projectId) {
      this.instance.projectId = projectId;
      return this;
    }
    public Label.Builder creationTime(Date creationTime) {
      this.instance.creationTime = creationTime;
      return this;
    }
    public Label.Builder updateTime(Date updateTime) {
      this.instance.updateTime = updateTime;
      return this;
    }


    /**
    * returns a built Label instance.
    *
    * The builder is not reusable.
    */
    public Label build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Label.Builder builder() {
    return new Label.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Label.Builder toBuilder() {
    return new Label.Builder()
      .id(getId())
      .name(getName())
      .description(getDescription())
      .color(getColor())
      .scope(getScope())
      .projectId(getProjectId())
      .creationTime(getCreationTime())
      .updateTime(getUpdateTime());
  }


}

