/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.Scanner;
import com.ryan.openapi.harbor.client.model.VulnerabilitySummary;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The summary for the native report
 */
@JsonPropertyOrder({
  NativeReportSummary.JSON_PROPERTY_REPORT_ID,
  NativeReportSummary.JSON_PROPERTY_SCAN_STATUS,
  NativeReportSummary.JSON_PROPERTY_SEVERITY,
  NativeReportSummary.JSON_PROPERTY_DURATION,
  NativeReportSummary.JSON_PROPERTY_SUMMARY,
  NativeReportSummary.JSON_PROPERTY_START_TIME,
  NativeReportSummary.JSON_PROPERTY_END_TIME,
  NativeReportSummary.JSON_PROPERTY_COMPLETE_PERCENT,
  NativeReportSummary.JSON_PROPERTY_SCANNER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class NativeReportSummary {
  public static final String JSON_PROPERTY_REPORT_ID = "report_id";
  @jakarta.annotation.Nullable
  private String reportId;

  public static final String JSON_PROPERTY_SCAN_STATUS = "scan_status";
  @jakarta.annotation.Nullable
  private String scanStatus;

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  @jakarta.annotation.Nullable
  private String severity;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Long duration;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @jakarta.annotation.Nullable
  private VulnerabilitySummary summary;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Date startTime;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  @jakarta.annotation.Nullable
  private Date endTime;

  public static final String JSON_PROPERTY_COMPLETE_PERCENT = "complete_percent";
  @jakarta.annotation.Nullable
  private Integer completePercent;

  public static final String JSON_PROPERTY_SCANNER = "scanner";
  @jakarta.annotation.Nullable
  private Scanner scanner;

  public NativeReportSummary() {
  }

  public NativeReportSummary reportId(@jakarta.annotation.Nullable String reportId) {
    
    this.reportId = reportId;
    return this;
  }

  /**
   * id of the native scan report
   * @return reportId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPORT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportId() {
    return reportId;
  }


  @JsonProperty(value = JSON_PROPERTY_REPORT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportId(@jakarta.annotation.Nullable String reportId) {
    this.reportId = reportId;
  }

  public NativeReportSummary scanStatus(@jakarta.annotation.Nullable String scanStatus) {
    
    this.scanStatus = scanStatus;
    return this;
  }

  /**
   * The status of the report generating process
   * @return scanStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCAN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScanStatus() {
    return scanStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_SCAN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScanStatus(@jakarta.annotation.Nullable String scanStatus) {
    this.scanStatus = scanStatus;
  }

  public NativeReportSummary severity(@jakarta.annotation.Nullable String severity) {
    
    this.severity = severity;
    return this;
  }

  /**
   * The overall severity
   * @return severity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeverity() {
    return severity;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverity(@jakarta.annotation.Nullable String severity) {
    this.severity = severity;
  }

  public NativeReportSummary duration(@jakarta.annotation.Nullable Long duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * The seconds spent for generating the report
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
  }

  public NativeReportSummary summary(@jakarta.annotation.Nullable VulnerabilitySummary summary) {
    
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VulnerabilitySummary getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@jakarta.annotation.Nullable VulnerabilitySummary summary) {
    this.summary = summary;
  }

  public NativeReportSummary startTime(@jakarta.annotation.Nullable Date startTime) {
    
    this.startTime = startTime;
    return this;
  }

  /**
   * The start time of the scan process that generating report
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getStartTime() {
    return startTime;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Date startTime) {
    this.startTime = startTime;
  }

  public NativeReportSummary endTime(@jakarta.annotation.Nullable Date endTime) {
    
    this.endTime = endTime;
    return this;
  }

  /**
   * The end time of the scan process that generating report
   * @return endTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getEndTime() {
    return endTime;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@jakarta.annotation.Nullable Date endTime) {
    this.endTime = endTime;
  }

  public NativeReportSummary completePercent(@jakarta.annotation.Nullable Integer completePercent) {
    
    this.completePercent = completePercent;
    return this;
  }

  /**
   * The complete percent of the scanning which value is between 0 and 100
   * @return completePercent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPLETE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCompletePercent() {
    return completePercent;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPLETE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompletePercent(@jakarta.annotation.Nullable Integer completePercent) {
    this.completePercent = completePercent;
  }

  public NativeReportSummary scanner(@jakarta.annotation.Nullable Scanner scanner) {
    
    this.scanner = scanner;
    return this;
  }

  /**
   * Get scanner
   * @return scanner
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCANNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Scanner getScanner() {
    return scanner;
  }


  @JsonProperty(value = JSON_PROPERTY_SCANNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScanner(@jakarta.annotation.Nullable Scanner scanner) {
    this.scanner = scanner;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NativeReportSummary nativeReportSummary = (NativeReportSummary) o;
    return Objects.equals(this.reportId, nativeReportSummary.reportId) &&
        Objects.equals(this.scanStatus, nativeReportSummary.scanStatus) &&
        Objects.equals(this.severity, nativeReportSummary.severity) &&
        Objects.equals(this.duration, nativeReportSummary.duration) &&
        Objects.equals(this.summary, nativeReportSummary.summary) &&
        Objects.equals(this.startTime, nativeReportSummary.startTime) &&
        Objects.equals(this.endTime, nativeReportSummary.endTime) &&
        Objects.equals(this.completePercent, nativeReportSummary.completePercent) &&
        Objects.equals(this.scanner, nativeReportSummary.scanner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportId, scanStatus, severity, duration, summary, startTime, endTime, completePercent, scanner);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NativeReportSummary {\n");
    sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
    sb.append("    scanStatus: ").append(toIndentedString(scanStatus)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    completePercent: ").append(toIndentedString(completePercent)).append("\n");
    sb.append("    scanner: ").append(toIndentedString(scanner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private NativeReportSummary instance;

    public Builder() {
      this(new NativeReportSummary());
    }

    protected Builder(NativeReportSummary instance) {
      this.instance = instance;
    }

    public NativeReportSummary.Builder reportId(String reportId) {
      this.instance.reportId = reportId;
      return this;
    }
    public NativeReportSummary.Builder scanStatus(String scanStatus) {
      this.instance.scanStatus = scanStatus;
      return this;
    }
    public NativeReportSummary.Builder severity(String severity) {
      this.instance.severity = severity;
      return this;
    }
    public NativeReportSummary.Builder duration(Long duration) {
      this.instance.duration = duration;
      return this;
    }
    public NativeReportSummary.Builder summary(VulnerabilitySummary summary) {
      this.instance.summary = summary;
      return this;
    }
    public NativeReportSummary.Builder startTime(Date startTime) {
      this.instance.startTime = startTime;
      return this;
    }
    public NativeReportSummary.Builder endTime(Date endTime) {
      this.instance.endTime = endTime;
      return this;
    }
    public NativeReportSummary.Builder completePercent(Integer completePercent) {
      this.instance.completePercent = completePercent;
      return this;
    }
    public NativeReportSummary.Builder scanner(Scanner scanner) {
      this.instance.scanner = scanner;
      return this;
    }


    /**
    * returns a built NativeReportSummary instance.
    *
    * The builder is not reusable.
    */
    public NativeReportSummary build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static NativeReportSummary.Builder builder() {
    return new NativeReportSummary.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public NativeReportSummary.Builder toBuilder() {
    return new NativeReportSummary.Builder()
      .reportId(getReportId())
      .scanStatus(getScanStatus())
      .severity(getSeverity())
      .duration(getDuration())
      .summary(getSummary())
      .startTime(getStartTime())
      .endTime(getEndTime())
      .completePercent(getCompletePercent())
      .scanner(getScanner());
  }


}

