/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OperateRetentionExecutionRequest
 */
@JsonPropertyOrder({
  OperateRetentionExecutionRequest.JSON_PROPERTY_ACTION
})
@JsonTypeName("operateRetentionExecution_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class OperateRetentionExecutionRequest {
  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nullable
  private String action;

  public OperateRetentionExecutionRequest() {
  }

  public OperateRetentionExecutionRequest action(@jakarta.annotation.Nullable String action) {
    
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(@jakarta.annotation.Nullable String action) {
    this.action = action;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperateRetentionExecutionRequest operateRetentionExecutionRequest = (OperateRetentionExecutionRequest) o;
    return Objects.equals(this.action, operateRetentionExecutionRequest.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperateRetentionExecutionRequest {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private OperateRetentionExecutionRequest instance;

    public Builder() {
      this(new OperateRetentionExecutionRequest());
    }

    protected Builder(OperateRetentionExecutionRequest instance) {
      this.instance = instance;
    }

    public OperateRetentionExecutionRequest.Builder action(String action) {
      this.instance.action = action;
      return this;
    }


    /**
    * returns a built OperateRetentionExecutionRequest instance.
    *
    * The builder is not reusable.
    */
    public OperateRetentionExecutionRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static OperateRetentionExecutionRequest.Builder builder() {
    return new OperateRetentionExecutionRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public OperateRetentionExecutionRequest.Builder toBuilder() {
    return new OperateRetentionExecutionRequest.Builder()
      .action(getAction());
  }


}

