/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.ComponentHealthStatus;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The system health status
 */
@JsonPropertyOrder({
  OverallHealthStatus.JSON_PROPERTY_STATUS,
  OverallHealthStatus.JSON_PROPERTY_COMPONENTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class OverallHealthStatus {
  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_COMPONENTS = "components";
  @jakarta.annotation.Nullable
  private List<ComponentHealthStatus> components = new ArrayList<>();

  public OverallHealthStatus() {
  }

  public OverallHealthStatus status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * The overall health status. It is \&quot;healthy\&quot; only when all the components&#39; status are \&quot;healthy\&quot;
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }

  public OverallHealthStatus components(@jakarta.annotation.Nullable List<ComponentHealthStatus> components) {
    
    this.components = components;
    return this;
  }

  public OverallHealthStatus addComponentsItem(ComponentHealthStatus componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

  /**
   * Get components
   * @return components
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPONENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ComponentHealthStatus> getComponents() {
    return components;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPONENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponents(@jakarta.annotation.Nullable List<ComponentHealthStatus> components) {
    this.components = components;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OverallHealthStatus overallHealthStatus = (OverallHealthStatus) o;
    return Objects.equals(this.status, overallHealthStatus.status) &&
        Objects.equals(this.components, overallHealthStatus.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, components);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OverallHealthStatus {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private OverallHealthStatus instance;

    public Builder() {
      this(new OverallHealthStatus());
    }

    protected Builder(OverallHealthStatus instance) {
      this.instance = instance;
    }

    public OverallHealthStatus.Builder status(String status) {
      this.instance.status = status;
      return this;
    }
    public OverallHealthStatus.Builder components(List<ComponentHealthStatus> components) {
      this.instance.components = components;
      return this;
    }


    /**
    * returns a built OverallHealthStatus instance.
    *
    * The builder is not reusable.
    */
    public OverallHealthStatus build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static OverallHealthStatus.Builder builder() {
    return new OverallHealthStatus.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public OverallHealthStatus.Builder toBuilder() {
    return new OverallHealthStatus.Builder()
      .status(getStatus())
      .components(getComponents());
  }


}

