/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PasswordReq
 */
@JsonPropertyOrder({
  PasswordReq.JSON_PROPERTY_OLD_PASSWORD,
  PasswordReq.JSON_PROPERTY_NEW_PASSWORD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PasswordReq {
  public static final String JSON_PROPERTY_OLD_PASSWORD = "old_password";
  @jakarta.annotation.Nullable
  private String oldPassword;

  public static final String JSON_PROPERTY_NEW_PASSWORD = "new_password";
  @jakarta.annotation.Nullable
  private String newPassword;

  public PasswordReq() {
  }

  public PasswordReq oldPassword(@jakarta.annotation.Nullable String oldPassword) {
    
    this.oldPassword = oldPassword;
    return this;
  }

  /**
   * The user&#39;s existing password.
   * @return oldPassword
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OLD_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOldPassword() {
    return oldPassword;
  }


  @JsonProperty(value = JSON_PROPERTY_OLD_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOldPassword(@jakarta.annotation.Nullable String oldPassword) {
    this.oldPassword = oldPassword;
  }

  public PasswordReq newPassword(@jakarta.annotation.Nullable String newPassword) {
    
    this.newPassword = newPassword;
    return this;
  }

  /**
   * New password for marking as to be updated.
   * @return newPassword
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEW_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNewPassword() {
    return newPassword;
  }


  @JsonProperty(value = JSON_PROPERTY_NEW_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewPassword(@jakarta.annotation.Nullable String newPassword) {
    this.newPassword = newPassword;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordReq passwordReq = (PasswordReq) o;
    return Objects.equals(this.oldPassword, passwordReq.oldPassword) &&
        Objects.equals(this.newPassword, passwordReq.newPassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldPassword, newPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordReq {\n");
    sb.append("    oldPassword: ").append(toIndentedString(oldPassword)).append("\n");
    sb.append("    newPassword: ").append(toIndentedString(newPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private PasswordReq instance;

    public Builder() {
      this(new PasswordReq());
    }

    protected Builder(PasswordReq instance) {
      this.instance = instance;
    }

    public PasswordReq.Builder oldPassword(String oldPassword) {
      this.instance.oldPassword = oldPassword;
      return this;
    }
    public PasswordReq.Builder newPassword(String newPassword) {
      this.instance.newPassword = newPassword;
      return this;
    }


    /**
    * returns a built PasswordReq instance.
    *
    * The builder is not reusable.
    */
    public PasswordReq build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PasswordReq.Builder builder() {
    return new PasswordReq.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PasswordReq.Builder toBuilder() {
    return new PasswordReq.Builder()
      .oldPassword(getOldPassword())
      .newPassword(getNewPassword());
  }


}

