/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProjectMemberEntity
 */
@JsonPropertyOrder({
  ProjectMemberEntity.JSON_PROPERTY_ID,
  ProjectMemberEntity.JSON_PROPERTY_PROJECT_ID,
  ProjectMemberEntity.JSON_PROPERTY_ENTITY_NAME,
  ProjectMemberEntity.JSON_PROPERTY_ROLE_NAME,
  ProjectMemberEntity.JSON_PROPERTY_ROLE_ID,
  ProjectMemberEntity.JSON_PROPERTY_ENTITY_ID,
  ProjectMemberEntity.JSON_PROPERTY_ENTITY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ProjectMemberEntity {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_ENTITY_NAME = "entity_name";
  @jakarta.annotation.Nullable
  private String entityName;

  public static final String JSON_PROPERTY_ROLE_NAME = "role_name";
  @jakarta.annotation.Nullable
  private String roleName;

  public static final String JSON_PROPERTY_ROLE_ID = "role_id";
  @jakarta.annotation.Nullable
  private Integer roleId;

  public static final String JSON_PROPERTY_ENTITY_ID = "entity_id";
  @jakarta.annotation.Nullable
  private Integer entityId;

  public static final String JSON_PROPERTY_ENTITY_TYPE = "entity_type";
  @jakarta.annotation.Nullable
  private String entityType;

  public ProjectMemberEntity() {
  }

  public ProjectMemberEntity id(@jakarta.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * the project member id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }

  public ProjectMemberEntity projectId(@jakarta.annotation.Nullable Integer projectId) {
    
    this.projectId = projectId;
    return this;
  }

  /**
   * the project id
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }

  public ProjectMemberEntity entityName(@jakarta.annotation.Nullable String entityName) {
    
    this.entityName = entityName;
    return this;
  }

  /**
   * the name of the group member.
   * @return entityName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEntityName() {
    return entityName;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityName(@jakarta.annotation.Nullable String entityName) {
    this.entityName = entityName;
  }

  public ProjectMemberEntity roleName(@jakarta.annotation.Nullable String roleName) {
    
    this.roleName = roleName;
    return this;
  }

  /**
   * the name of the role
   * @return roleName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoleName() {
    return roleName;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoleName(@jakarta.annotation.Nullable String roleName) {
    this.roleName = roleName;
  }

  public ProjectMemberEntity roleId(@jakarta.annotation.Nullable Integer roleId) {
    
    this.roleId = roleId;
    return this;
  }

  /**
   * the role id
   * @return roleId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRoleId() {
    return roleId;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoleId(@jakarta.annotation.Nullable Integer roleId) {
    this.roleId = roleId;
  }

  public ProjectMemberEntity entityId(@jakarta.annotation.Nullable Integer entityId) {
    
    this.entityId = entityId;
    return this;
  }

  /**
   * the id of entity, if the member is a user, it is user_id in user table. if the member is a user group, it is the user group&#39;s ID in user_group table.
   * @return entityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEntityId() {
    return entityId;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityId(@jakarta.annotation.Nullable Integer entityId) {
    this.entityId = entityId;
  }

  public ProjectMemberEntity entityType(@jakarta.annotation.Nullable String entityType) {
    
    this.entityType = entityType;
    return this;
  }

  /**
   * the entity&#39;s type, u for user entity, g for group entity.
   * @return entityType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEntityType() {
    return entityType;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityType(@jakarta.annotation.Nullable String entityType) {
    this.entityType = entityType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectMemberEntity projectMemberEntity = (ProjectMemberEntity) o;
    return Objects.equals(this.id, projectMemberEntity.id) &&
        Objects.equals(this.projectId, projectMemberEntity.projectId) &&
        Objects.equals(this.entityName, projectMemberEntity.entityName) &&
        Objects.equals(this.roleName, projectMemberEntity.roleName) &&
        Objects.equals(this.roleId, projectMemberEntity.roleId) &&
        Objects.equals(this.entityId, projectMemberEntity.entityId) &&
        Objects.equals(this.entityType, projectMemberEntity.entityType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, entityName, roleName, roleId, entityId, entityType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectMemberEntity {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    roleName: ").append(toIndentedString(roleName)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ProjectMemberEntity instance;

    public Builder() {
      this(new ProjectMemberEntity());
    }

    protected Builder(ProjectMemberEntity instance) {
      this.instance = instance;
    }

    public ProjectMemberEntity.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public ProjectMemberEntity.Builder projectId(Integer projectId) {
      this.instance.projectId = projectId;
      return this;
    }
    public ProjectMemberEntity.Builder entityName(String entityName) {
      this.instance.entityName = entityName;
      return this;
    }
    public ProjectMemberEntity.Builder roleName(String roleName) {
      this.instance.roleName = roleName;
      return this;
    }
    public ProjectMemberEntity.Builder roleId(Integer roleId) {
      this.instance.roleId = roleId;
      return this;
    }
    public ProjectMemberEntity.Builder entityId(Integer entityId) {
      this.instance.entityId = entityId;
      return this;
    }
    public ProjectMemberEntity.Builder entityType(String entityType) {
      this.instance.entityType = entityType;
      return this;
    }


    /**
    * returns a built ProjectMemberEntity instance.
    *
    * The builder is not reusable.
    */
    public ProjectMemberEntity build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ProjectMemberEntity.Builder builder() {
    return new ProjectMemberEntity.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ProjectMemberEntity.Builder toBuilder() {
    return new ProjectMemberEntity.Builder()
      .id(getId())
      .projectId(getProjectId())
      .entityName(getEntityName())
      .roleName(getRoleName())
      .roleId(getRoleId())
      .entityId(getEntityId())
      .entityType(getEntityType());
  }


}

