/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.CVEAllowlist;
import com.ryan.openapi.harbor.client.model.ProjectMetadata;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProjectReq
 */
@JsonPropertyOrder({
  ProjectReq.JSON_PROPERTY_PROJECT_NAME,
  ProjectReq.JSON_PROPERTY_PUBLIC,
  ProjectReq.JSON_PROPERTY_METADATA,
  ProjectReq.JSON_PROPERTY_CVE_ALLOWLIST,
  ProjectReq.JSON_PROPERTY_STORAGE_LIMIT,
  ProjectReq.JSON_PROPERTY_REGISTRY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ProjectReq {
  public static final String JSON_PROPERTY_PROJECT_NAME = "project_name";
  @jakarta.annotation.Nullable
  private String projectName;

  public static final String JSON_PROPERTY_PUBLIC = "public";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> _public = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private ProjectMetadata metadata;

  public static final String JSON_PROPERTY_CVE_ALLOWLIST = "cve_allowlist";
  @jakarta.annotation.Nullable
  private CVEAllowlist cveAllowlist;

  public static final String JSON_PROPERTY_STORAGE_LIMIT = "storage_limit";
  @jakarta.annotation.Nullable
  private JsonNullable<Long> storageLimit = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_REGISTRY_ID = "registry_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Long> registryId = JsonNullable.<Long>undefined();

  public ProjectReq() {
  }

  public ProjectReq projectName(@jakarta.annotation.Nullable String projectName) {
    
    this.projectName = projectName;
    return this;
  }

  /**
   * The name of the project.
   * @return projectName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectName() {
    return projectName;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectName(@jakarta.annotation.Nullable String projectName) {
    this.projectName = projectName;
  }

  public ProjectReq _public(@jakarta.annotation.Nullable Boolean _public) {
    this._public = JsonNullable.<Boolean>of(_public);
    
    return this;
  }

  /**
   * deprecated, reserved for project creation in replication
   * @return _public
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getPublic() {
        return _public.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PUBLIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getPublic_JsonNullable() {
    return _public;
  }
  
  @JsonProperty(JSON_PROPERTY_PUBLIC)
  public void setPublic_JsonNullable(JsonNullable<Boolean> _public) {
    this._public = _public;
  }

  public void setPublic(@jakarta.annotation.Nullable Boolean _public) {
    this._public = JsonNullable.<Boolean>of(_public);
  }

  public ProjectReq metadata(@jakarta.annotation.Nullable ProjectMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectMetadata getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable ProjectMetadata metadata) {
    this.metadata = metadata;
  }

  public ProjectReq cveAllowlist(@jakarta.annotation.Nullable CVEAllowlist cveAllowlist) {
    
    this.cveAllowlist = cveAllowlist;
    return this;
  }

  /**
   * Get cveAllowlist
   * @return cveAllowlist
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CVE_ALLOWLIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CVEAllowlist getCveAllowlist() {
    return cveAllowlist;
  }


  @JsonProperty(value = JSON_PROPERTY_CVE_ALLOWLIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCveAllowlist(@jakarta.annotation.Nullable CVEAllowlist cveAllowlist) {
    this.cveAllowlist = cveAllowlist;
  }

  public ProjectReq storageLimit(@jakarta.annotation.Nullable Long storageLimit) {
    this.storageLimit = JsonNullable.<Long>of(storageLimit);
    
    return this;
  }

  /**
   * The storage quota of the project.
   * @return storageLimit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getStorageLimit() {
        return storageLimit.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STORAGE_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getStorageLimit_JsonNullable() {
    return storageLimit;
  }
  
  @JsonProperty(JSON_PROPERTY_STORAGE_LIMIT)
  public void setStorageLimit_JsonNullable(JsonNullable<Long> storageLimit) {
    this.storageLimit = storageLimit;
  }

  public void setStorageLimit(@jakarta.annotation.Nullable Long storageLimit) {
    this.storageLimit = JsonNullable.<Long>of(storageLimit);
  }

  public ProjectReq registryId(@jakarta.annotation.Nullable Long registryId) {
    this.registryId = JsonNullable.<Long>of(registryId);
    
    return this;
  }

  /**
   * The ID of referenced registry when creating the proxy cache project
   * @return registryId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getRegistryId() {
        return registryId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REGISTRY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getRegistryId_JsonNullable() {
    return registryId;
  }
  
  @JsonProperty(JSON_PROPERTY_REGISTRY_ID)
  public void setRegistryId_JsonNullable(JsonNullable<Long> registryId) {
    this.registryId = registryId;
  }

  public void setRegistryId(@jakarta.annotation.Nullable Long registryId) {
    this.registryId = JsonNullable.<Long>of(registryId);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectReq projectReq = (ProjectReq) o;
    return Objects.equals(this.projectName, projectReq.projectName) &&
        equalsNullable(this._public, projectReq._public) &&
        Objects.equals(this.metadata, projectReq.metadata) &&
        Objects.equals(this.cveAllowlist, projectReq.cveAllowlist) &&
        equalsNullable(this.storageLimit, projectReq.storageLimit) &&
        equalsNullable(this.registryId, projectReq.registryId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectName, hashCodeNullable(_public), metadata, cveAllowlist, hashCodeNullable(storageLimit), hashCodeNullable(registryId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectReq {\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    cveAllowlist: ").append(toIndentedString(cveAllowlist)).append("\n");
    sb.append("    storageLimit: ").append(toIndentedString(storageLimit)).append("\n");
    sb.append("    registryId: ").append(toIndentedString(registryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ProjectReq instance;

    public Builder() {
      this(new ProjectReq());
    }

    protected Builder(ProjectReq instance) {
      this.instance = instance;
    }

    public ProjectReq.Builder projectName(String projectName) {
      this.instance.projectName = projectName;
      return this;
    }
    public ProjectReq.Builder _public(Boolean _public) {
      this.instance._public = JsonNullable.<Boolean>of(_public);
      return this;
    }
    public ProjectReq.Builder _public(JsonNullable<Boolean> _public) {
      this.instance._public = _public;
      return this;
    }
    public ProjectReq.Builder metadata(ProjectMetadata metadata) {
      this.instance.metadata = metadata;
      return this;
    }
    public ProjectReq.Builder cveAllowlist(CVEAllowlist cveAllowlist) {
      this.instance.cveAllowlist = cveAllowlist;
      return this;
    }
    public ProjectReq.Builder storageLimit(Long storageLimit) {
      this.instance.storageLimit = JsonNullable.<Long>of(storageLimit);
      return this;
    }
    public ProjectReq.Builder storageLimit(JsonNullable<Long> storageLimit) {
      this.instance.storageLimit = storageLimit;
      return this;
    }
    public ProjectReq.Builder registryId(Long registryId) {
      this.instance.registryId = JsonNullable.<Long>of(registryId);
      return this;
    }
    public ProjectReq.Builder registryId(JsonNullable<Long> registryId) {
      this.instance.registryId = registryId;
      return this;
    }


    /**
    * returns a built ProjectReq instance.
    *
    * The builder is not reusable.
    */
    public ProjectReq build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ProjectReq.Builder builder() {
    return new ProjectReq.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ProjectReq.Builder toBuilder() {
    return new ProjectReq.Builder()
      .projectName(getProjectName())
      ._public(getPublic())
      .metadata(getMetadata())
      .cveAllowlist(getCveAllowlist())
      .storageLimit(getStorageLimit())
      .registryId(getRegistryId());
  }


}

