/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The quota object
 */
@JsonPropertyOrder({
  Quota.JSON_PROPERTY_ID,
  Quota.JSON_PROPERTY_REF,
  Quota.JSON_PROPERTY_HARD,
  Quota.JSON_PROPERTY_USED,
  Quota.JSON_PROPERTY_CREATION_TIME,
  Quota.JSON_PROPERTY_UPDATE_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Quota {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_REF = "ref";
  @jakarta.annotation.Nullable
  private Map<String, Object> ref = new HashMap<>();

  public static final String JSON_PROPERTY_HARD = "hard";
  @jakarta.annotation.Nullable
  private Map<String, Long> hard = new HashMap<>();

  public static final String JSON_PROPERTY_USED = "used";
  @jakarta.annotation.Nullable
  private Map<String, Long> used = new HashMap<>();

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @jakarta.annotation.Nullable
  private Date creationTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  @jakarta.annotation.Nullable
  private Date updateTime;

  public Quota() {
  }

  public Quota id(@jakarta.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * ID of the quota
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }

  public Quota ref(@jakarta.annotation.Nullable Map<String, Object> ref) {
    
    this.ref = ref;
    return this;
  }

  public Quota putRefItem(String key, Object refItem) {
    if (this.ref == null) {
      this.ref = new HashMap<>();
    }
    this.ref.put(key, refItem);
    return this;
  }

  /**
   * Get ref
   * @return ref
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getRef() {
    return ref;
  }


  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRef(@jakarta.annotation.Nullable Map<String, Object> ref) {
    this.ref = ref;
  }

  public Quota hard(@jakarta.annotation.Nullable Map<String, Long> hard) {
    
    this.hard = hard;
    return this;
  }

  public Quota putHardItem(String key, Long hardItem) {
    if (this.hard == null) {
      this.hard = new HashMap<>();
    }
    this.hard.put(key, hardItem);
    return this;
  }

  /**
   * Get hard
   * @return hard
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Long> getHard() {
    return hard;
  }


  @JsonProperty(value = JSON_PROPERTY_HARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHard(@jakarta.annotation.Nullable Map<String, Long> hard) {
    this.hard = hard;
  }

  public Quota used(@jakarta.annotation.Nullable Map<String, Long> used) {
    
    this.used = used;
    return this;
  }

  public Quota putUsedItem(String key, Long usedItem) {
    if (this.used == null) {
      this.used = new HashMap<>();
    }
    this.used.put(key, usedItem);
    return this;
  }

  /**
   * Get used
   * @return used
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Long> getUsed() {
    return used;
  }


  @JsonProperty(value = JSON_PROPERTY_USED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsed(@jakarta.annotation.Nullable Map<String, Long> used) {
    this.used = used;
  }

  public Quota creationTime(@jakarta.annotation.Nullable Date creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

  /**
   * the creation time of the quota
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Date creationTime) {
    this.creationTime = creationTime;
  }

  public Quota updateTime(@jakarta.annotation.Nullable Date updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

  /**
   * the update time of the quota
   * @return updateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(@jakarta.annotation.Nullable Date updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Quota quota = (Quota) o;
    return Objects.equals(this.id, quota.id) &&
        Objects.equals(this.ref, quota.ref) &&
        Objects.equals(this.hard, quota.hard) &&
        Objects.equals(this.used, quota.used) &&
        Objects.equals(this.creationTime, quota.creationTime) &&
        Objects.equals(this.updateTime, quota.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ref, hard, used, creationTime, updateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Quota {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    hard: ").append(toIndentedString(hard)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Quota instance;

    public Builder() {
      this(new Quota());
    }

    protected Builder(Quota instance) {
      this.instance = instance;
    }

    public Quota.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public Quota.Builder ref(Map<String, Object> ref) {
      this.instance.ref = ref;
      return this;
    }
    public Quota.Builder hard(Map<String, Long> hard) {
      this.instance.hard = hard;
      return this;
    }
    public Quota.Builder used(Map<String, Long> used) {
      this.instance.used = used;
      return this;
    }
    public Quota.Builder creationTime(Date creationTime) {
      this.instance.creationTime = creationTime;
      return this;
    }
    public Quota.Builder updateTime(Date updateTime) {
      this.instance.updateTime = updateTime;
      return this;
    }


    /**
    * returns a built Quota instance.
    *
    * The builder is not reusable.
    */
    public Quota build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Quota.Builder builder() {
    return new Quota.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Quota.Builder toBuilder() {
    return new Quota.Builder()
      .id(getId())
      .ref(getRef())
      .hard(getHard())
      .used(getUsed())
      .creationTime(getCreationTime())
      .updateTime(getUpdateTime());
  }


}

