/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RegistryPing
 */
@JsonPropertyOrder({
  RegistryPing.JSON_PROPERTY_ID,
  RegistryPing.JSON_PROPERTY_TYPE,
  RegistryPing.JSON_PROPERTY_URL,
  RegistryPing.JSON_PROPERTY_CREDENTIAL_TYPE,
  RegistryPing.JSON_PROPERTY_ACCESS_KEY,
  RegistryPing.JSON_PROPERTY_ACCESS_SECRET,
  RegistryPing.JSON_PROPERTY_INSECURE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RegistryPing {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private JsonNullable<Long> id = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private JsonNullable<String> type = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private JsonNullable<String> url = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CREDENTIAL_TYPE = "credential_type";
  @jakarta.annotation.Nullable
  private JsonNullable<String> credentialType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ACCESS_KEY = "access_key";
  @jakarta.annotation.Nullable
  private JsonNullable<String> accessKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ACCESS_SECRET = "access_secret";
  @jakarta.annotation.Nullable
  private JsonNullable<String> accessSecret = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INSECURE = "insecure";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> insecure = JsonNullable.<Boolean>undefined();

  public RegistryPing() {
  }

  public RegistryPing id(@jakarta.annotation.Nullable Long id) {
    this.id = JsonNullable.<Long>of(id);
    
    return this;
  }

  /**
   * The registry ID.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getId() {
        return id.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getId_JsonNullable() {
    return id;
  }
  
  @JsonProperty(JSON_PROPERTY_ID)
  public void setId_JsonNullable(JsonNullable<Long> id) {
    this.id = id;
  }

  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = JsonNullable.<Long>of(id);
  }

  public RegistryPing type(@jakarta.annotation.Nullable String type) {
    this.type = JsonNullable.<String>of(type);
    
    return this;
  }

  /**
   * Type of the registry, e.g. &#39;harbor&#39;.
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getType() {
        return type.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getType_JsonNullable() {
    return type;
  }
  
  @JsonProperty(JSON_PROPERTY_TYPE)
  public void setType_JsonNullable(JsonNullable<String> type) {
    this.type = type;
  }

  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = JsonNullable.<String>of(type);
  }

  public RegistryPing url(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
    
    return this;
  }

  /**
   * The registry URL.
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUrl() {
        return url.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUrl_JsonNullable() {
    return url;
  }
  
  @JsonProperty(JSON_PROPERTY_URL)
  public void setUrl_JsonNullable(JsonNullable<String> url) {
    this.url = url;
  }

  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
  }

  public RegistryPing credentialType(@jakarta.annotation.Nullable String credentialType) {
    this.credentialType = JsonNullable.<String>of(credentialType);
    
    return this;
  }

  /**
   * Credential type of the registry, e.g. &#39;basic&#39;.
   * @return credentialType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getCredentialType() {
        return credentialType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCredentialType_JsonNullable() {
    return credentialType;
  }
  
  @JsonProperty(JSON_PROPERTY_CREDENTIAL_TYPE)
  public void setCredentialType_JsonNullable(JsonNullable<String> credentialType) {
    this.credentialType = credentialType;
  }

  public void setCredentialType(@jakarta.annotation.Nullable String credentialType) {
    this.credentialType = JsonNullable.<String>of(credentialType);
  }

  public RegistryPing accessKey(@jakarta.annotation.Nullable String accessKey) {
    this.accessKey = JsonNullable.<String>of(accessKey);
    
    return this;
  }

  /**
   * The registry access key.
   * @return accessKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAccessKey() {
        return accessKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ACCESS_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAccessKey_JsonNullable() {
    return accessKey;
  }
  
  @JsonProperty(JSON_PROPERTY_ACCESS_KEY)
  public void setAccessKey_JsonNullable(JsonNullable<String> accessKey) {
    this.accessKey = accessKey;
  }

  public void setAccessKey(@jakarta.annotation.Nullable String accessKey) {
    this.accessKey = JsonNullable.<String>of(accessKey);
  }

  public RegistryPing accessSecret(@jakarta.annotation.Nullable String accessSecret) {
    this.accessSecret = JsonNullable.<String>of(accessSecret);
    
    return this;
  }

  /**
   * The registry access secret.
   * @return accessSecret
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAccessSecret() {
        return accessSecret.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ACCESS_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAccessSecret_JsonNullable() {
    return accessSecret;
  }
  
  @JsonProperty(JSON_PROPERTY_ACCESS_SECRET)
  public void setAccessSecret_JsonNullable(JsonNullable<String> accessSecret) {
    this.accessSecret = accessSecret;
  }

  public void setAccessSecret(@jakarta.annotation.Nullable String accessSecret) {
    this.accessSecret = JsonNullable.<String>of(accessSecret);
  }

  public RegistryPing insecure(@jakarta.annotation.Nullable Boolean insecure) {
    this.insecure = JsonNullable.<Boolean>of(insecure);
    
    return this;
  }

  /**
   * Whether or not the certificate will be verified when Harbor tries to access the server.
   * @return insecure
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getInsecure() {
        return insecure.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_INSECURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getInsecure_JsonNullable() {
    return insecure;
  }
  
  @JsonProperty(JSON_PROPERTY_INSECURE)
  public void setInsecure_JsonNullable(JsonNullable<Boolean> insecure) {
    this.insecure = insecure;
  }

  public void setInsecure(@jakarta.annotation.Nullable Boolean insecure) {
    this.insecure = JsonNullable.<Boolean>of(insecure);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistryPing registryPing = (RegistryPing) o;
    return equalsNullable(this.id, registryPing.id) &&
        equalsNullable(this.type, registryPing.type) &&
        equalsNullable(this.url, registryPing.url) &&
        equalsNullable(this.credentialType, registryPing.credentialType) &&
        equalsNullable(this.accessKey, registryPing.accessKey) &&
        equalsNullable(this.accessSecret, registryPing.accessSecret) &&
        equalsNullable(this.insecure, registryPing.insecure);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(id), hashCodeNullable(type), hashCodeNullable(url), hashCodeNullable(credentialType), hashCodeNullable(accessKey), hashCodeNullable(accessSecret), hashCodeNullable(insecure));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistryPing {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    credentialType: ").append(toIndentedString(credentialType)).append("\n");
    sb.append("    accessKey: ").append(toIndentedString(accessKey)).append("\n");
    sb.append("    accessSecret: ").append(toIndentedString(accessSecret)).append("\n");
    sb.append("    insecure: ").append(toIndentedString(insecure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RegistryPing instance;

    public Builder() {
      this(new RegistryPing());
    }

    protected Builder(RegistryPing instance) {
      this.instance = instance;
    }

    public RegistryPing.Builder id(Long id) {
      this.instance.id = JsonNullable.<Long>of(id);
      return this;
    }
    public RegistryPing.Builder id(JsonNullable<Long> id) {
      this.instance.id = id;
      return this;
    }
    public RegistryPing.Builder type(String type) {
      this.instance.type = JsonNullable.<String>of(type);
      return this;
    }
    public RegistryPing.Builder type(JsonNullable<String> type) {
      this.instance.type = type;
      return this;
    }
    public RegistryPing.Builder url(String url) {
      this.instance.url = JsonNullable.<String>of(url);
      return this;
    }
    public RegistryPing.Builder url(JsonNullable<String> url) {
      this.instance.url = url;
      return this;
    }
    public RegistryPing.Builder credentialType(String credentialType) {
      this.instance.credentialType = JsonNullable.<String>of(credentialType);
      return this;
    }
    public RegistryPing.Builder credentialType(JsonNullable<String> credentialType) {
      this.instance.credentialType = credentialType;
      return this;
    }
    public RegistryPing.Builder accessKey(String accessKey) {
      this.instance.accessKey = JsonNullable.<String>of(accessKey);
      return this;
    }
    public RegistryPing.Builder accessKey(JsonNullable<String> accessKey) {
      this.instance.accessKey = accessKey;
      return this;
    }
    public RegistryPing.Builder accessSecret(String accessSecret) {
      this.instance.accessSecret = JsonNullable.<String>of(accessSecret);
      return this;
    }
    public RegistryPing.Builder accessSecret(JsonNullable<String> accessSecret) {
      this.instance.accessSecret = accessSecret;
      return this;
    }
    public RegistryPing.Builder insecure(Boolean insecure) {
      this.instance.insecure = JsonNullable.<Boolean>of(insecure);
      return this;
    }
    public RegistryPing.Builder insecure(JsonNullable<Boolean> insecure) {
      this.instance.insecure = insecure;
      return this;
    }


    /**
    * returns a built RegistryPing instance.
    *
    * The builder is not reusable.
    */
    public RegistryPing build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RegistryPing.Builder builder() {
    return new RegistryPing.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RegistryPing.Builder toBuilder() {
    return new RegistryPing.Builder()
      .id(getId())
      .type(getType())
      .url(getUrl())
      .credentialType(getCredentialType())
      .accessKey(getAccessKey())
      .accessSecret(getAccessSecret())
      .insecure(getInsecure());
  }


}

