/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.RegistryEndpoint;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The registry endpoint pattern
 */
@JsonPropertyOrder({
  RegistryProviderEndpointPattern.JSON_PROPERTY_ENDPOINT_TYPE,
  RegistryProviderEndpointPattern.JSON_PROPERTY_ENDPOINTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RegistryProviderEndpointPattern {
  public static final String JSON_PROPERTY_ENDPOINT_TYPE = "endpoint_type";
  @jakarta.annotation.Nullable
  private String endpointType;

  public static final String JSON_PROPERTY_ENDPOINTS = "endpoints";
  @jakarta.annotation.Nullable
  private List<RegistryEndpoint> endpoints = new ArrayList<>();

  public RegistryProviderEndpointPattern() {
  }

  public RegistryProviderEndpointPattern endpointType(@jakarta.annotation.Nullable String endpointType) {
    
    this.endpointType = endpointType;
    return this;
  }

  /**
   * The endpoint type
   * @return endpointType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndpointType() {
    return endpointType;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointType(@jakarta.annotation.Nullable String endpointType) {
    this.endpointType = endpointType;
  }

  public RegistryProviderEndpointPattern endpoints(@jakarta.annotation.Nullable List<RegistryEndpoint> endpoints) {
    
    this.endpoints = endpoints;
    return this;
  }

  public RegistryProviderEndpointPattern addEndpointsItem(RegistryEndpoint endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

  /**
   * The endpoint list
   * @return endpoints
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RegistryEndpoint> getEndpoints() {
    return endpoints;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoints(@jakarta.annotation.Nullable List<RegistryEndpoint> endpoints) {
    this.endpoints = endpoints;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistryProviderEndpointPattern registryProviderEndpointPattern = (RegistryProviderEndpointPattern) o;
    return Objects.equals(this.endpointType, registryProviderEndpointPattern.endpointType) &&
        Objects.equals(this.endpoints, registryProviderEndpointPattern.endpoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointType, endpoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistryProviderEndpointPattern {\n");
    sb.append("    endpointType: ").append(toIndentedString(endpointType)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RegistryProviderEndpointPattern instance;

    public Builder() {
      this(new RegistryProviderEndpointPattern());
    }

    protected Builder(RegistryProviderEndpointPattern instance) {
      this.instance = instance;
    }

    public RegistryProviderEndpointPattern.Builder endpointType(String endpointType) {
      this.instance.endpointType = endpointType;
      return this;
    }
    public RegistryProviderEndpointPattern.Builder endpoints(List<RegistryEndpoint> endpoints) {
      this.instance.endpoints = endpoints;
      return this;
    }


    /**
    * returns a built RegistryProviderEndpointPattern instance.
    *
    * The builder is not reusable.
    */
    public RegistryProviderEndpointPattern build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RegistryProviderEndpointPattern.Builder builder() {
    return new RegistryProviderEndpointPattern.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RegistryProviderEndpointPattern.Builder toBuilder() {
    return new RegistryProviderEndpointPattern.Builder()
      .endpointType(getEndpointType())
      .endpoints(getEndpoints());
  }


}

