/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.RegistryProviderCredentialPattern;
import com.ryan.openapi.harbor.client.model.RegistryProviderEndpointPattern;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The registry provider info contains the base info and capability declarations of the registry provider
 */
@JsonPropertyOrder({
  RegistryProviderInfo.JSON_PROPERTY_ENDPOINT_PATTERN,
  RegistryProviderInfo.JSON_PROPERTY_CREDENTIAL_PATTERN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RegistryProviderInfo {
  public static final String JSON_PROPERTY_ENDPOINT_PATTERN = "endpoint_pattern";
  @jakarta.annotation.Nullable
  private RegistryProviderEndpointPattern endpointPattern;

  public static final String JSON_PROPERTY_CREDENTIAL_PATTERN = "credential_pattern";
  @jakarta.annotation.Nullable
  private RegistryProviderCredentialPattern credentialPattern;

  public RegistryProviderInfo() {
  }

  public RegistryProviderInfo endpointPattern(@jakarta.annotation.Nullable RegistryProviderEndpointPattern endpointPattern) {
    
    this.endpointPattern = endpointPattern;
    return this;
  }

  /**
   * Get endpointPattern
   * @return endpointPattern
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegistryProviderEndpointPattern getEndpointPattern() {
    return endpointPattern;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointPattern(@jakarta.annotation.Nullable RegistryProviderEndpointPattern endpointPattern) {
    this.endpointPattern = endpointPattern;
  }

  public RegistryProviderInfo credentialPattern(@jakarta.annotation.Nullable RegistryProviderCredentialPattern credentialPattern) {
    
    this.credentialPattern = credentialPattern;
    return this;
  }

  /**
   * Get credentialPattern
   * @return credentialPattern
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegistryProviderCredentialPattern getCredentialPattern() {
    return credentialPattern;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredentialPattern(@jakarta.annotation.Nullable RegistryProviderCredentialPattern credentialPattern) {
    this.credentialPattern = credentialPattern;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistryProviderInfo registryProviderInfo = (RegistryProviderInfo) o;
    return Objects.equals(this.endpointPattern, registryProviderInfo.endpointPattern) &&
        Objects.equals(this.credentialPattern, registryProviderInfo.credentialPattern);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointPattern, credentialPattern);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistryProviderInfo {\n");
    sb.append("    endpointPattern: ").append(toIndentedString(endpointPattern)).append("\n");
    sb.append("    credentialPattern: ").append(toIndentedString(credentialPattern)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RegistryProviderInfo instance;

    public Builder() {
      this(new RegistryProviderInfo());
    }

    protected Builder(RegistryProviderInfo instance) {
      this.instance = instance;
    }

    public RegistryProviderInfo.Builder endpointPattern(RegistryProviderEndpointPattern endpointPattern) {
      this.instance.endpointPattern = endpointPattern;
      return this;
    }
    public RegistryProviderInfo.Builder credentialPattern(RegistryProviderCredentialPattern credentialPattern) {
      this.instance.credentialPattern = credentialPattern;
      return this;
    }


    /**
    * returns a built RegistryProviderInfo instance.
    *
    * The builder is not reusable.
    */
    public RegistryProviderInfo build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RegistryProviderInfo.Builder builder() {
    return new RegistryProviderInfo.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RegistryProviderInfo.Builder toBuilder() {
    return new RegistryProviderInfo.Builder()
      .endpointPattern(getEndpointPattern())
      .credentialPattern(getCredentialPattern());
  }


}

