/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.ReplicationTriggerSettings;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReplicationTrigger
 */
@JsonPropertyOrder({
  ReplicationTrigger.JSON_PROPERTY_TYPE,
  ReplicationTrigger.JSON_PROPERTY_TRIGGER_SETTINGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ReplicationTrigger {
  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_TRIGGER_SETTINGS = "trigger_settings";
  @jakarta.annotation.Nullable
  private ReplicationTriggerSettings triggerSettings;

  public ReplicationTrigger() {
  }

  public ReplicationTrigger type(@jakarta.annotation.Nullable String type) {
    
    this.type = type;
    return this;
  }

  /**
   * The replication policy trigger type. The valid values are manual, event_based and scheduled.
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }

  public ReplicationTrigger triggerSettings(@jakarta.annotation.Nullable ReplicationTriggerSettings triggerSettings) {
    
    this.triggerSettings = triggerSettings;
    return this;
  }

  /**
   * Get triggerSettings
   * @return triggerSettings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRIGGER_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReplicationTriggerSettings getTriggerSettings() {
    return triggerSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIGGER_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriggerSettings(@jakarta.annotation.Nullable ReplicationTriggerSettings triggerSettings) {
    this.triggerSettings = triggerSettings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplicationTrigger replicationTrigger = (ReplicationTrigger) o;
    return Objects.equals(this.type, replicationTrigger.type) &&
        Objects.equals(this.triggerSettings, replicationTrigger.triggerSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, triggerSettings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplicationTrigger {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    triggerSettings: ").append(toIndentedString(triggerSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ReplicationTrigger instance;

    public Builder() {
      this(new ReplicationTrigger());
    }

    protected Builder(ReplicationTrigger instance) {
      this.instance = instance;
    }

    public ReplicationTrigger.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public ReplicationTrigger.Builder triggerSettings(ReplicationTriggerSettings triggerSettings) {
      this.instance.triggerSettings = triggerSettings;
      return this;
    }


    /**
    * returns a built ReplicationTrigger instance.
    *
    * The builder is not reusable.
    */
    public ReplicationTrigger build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ReplicationTrigger.Builder builder() {
    return new ReplicationTrigger.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ReplicationTrigger.Builder toBuilder() {
    return new ReplicationTrigger.Builder()
      .type(getType())
      .triggerSettings(getTriggerSettings());
  }


}

