/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.RetentionSelector;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RetentionRule
 */
@JsonPropertyOrder({
  RetentionRule.JSON_PROPERTY_ID,
  RetentionRule.JSON_PROPERTY_PRIORITY,
  RetentionRule.JSON_PROPERTY_DISABLED,
  RetentionRule.JSON_PROPERTY_ACTION,
  RetentionRule.JSON_PROPERTY_TEMPLATE,
  RetentionRule.JSON_PROPERTY_PARAMS,
  RetentionRule.JSON_PROPERTY_TAG_SELECTORS,
  RetentionRule.JSON_PROPERTY_SCOPE_SELECTORS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RetentionRule {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  @jakarta.annotation.Nullable
  private Integer priority;

  public static final String JSON_PROPERTY_DISABLED = "disabled";
  @jakarta.annotation.Nullable
  private Boolean disabled;

  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nullable
  private String action;

  public static final String JSON_PROPERTY_TEMPLATE = "template";
  @jakarta.annotation.Nullable
  private String template;

  public static final String JSON_PROPERTY_PARAMS = "params";
  @jakarta.annotation.Nullable
  private Map<String, Object> params = new HashMap<>();

  public static final String JSON_PROPERTY_TAG_SELECTORS = "tag_selectors";
  @jakarta.annotation.Nullable
  private List<RetentionSelector> tagSelectors = new ArrayList<>();

  public static final String JSON_PROPERTY_SCOPE_SELECTORS = "scope_selectors";
  @jakarta.annotation.Nullable
  private Map<String, List<RetentionSelector>> scopeSelectors = new HashMap<>();

  public RetentionRule() {
  }

  public RetentionRule id(@jakarta.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }

  public RetentionRule priority(@jakarta.annotation.Nullable Integer priority) {
    
    this.priority = priority;
    return this;
  }

  /**
   * Get priority
   * @return priority
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIORITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPriority() {
    return priority;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIORITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriority(@jakarta.annotation.Nullable Integer priority) {
    this.priority = priority;
  }

  public RetentionRule disabled(@jakarta.annotation.Nullable Boolean disabled) {
    
    this.disabled = disabled;
    return this;
  }

  /**
   * Get disabled
   * @return disabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisabled() {
    return disabled;
  }


  @JsonProperty(value = JSON_PROPERTY_DISABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisabled(@jakarta.annotation.Nullable Boolean disabled) {
    this.disabled = disabled;
  }

  public RetentionRule action(@jakarta.annotation.Nullable String action) {
    
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(@jakarta.annotation.Nullable String action) {
    this.action = action;
  }

  public RetentionRule template(@jakarta.annotation.Nullable String template) {
    
    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTemplate() {
    return template;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplate(@jakarta.annotation.Nullable String template) {
    this.template = template;
  }

  public RetentionRule params(@jakarta.annotation.Nullable Map<String, Object> params) {
    
    this.params = params;
    return this;
  }

  public RetentionRule putParamsItem(String key, Object paramsItem) {
    if (this.params == null) {
      this.params = new HashMap<>();
    }
    this.params.put(key, paramsItem);
    return this;
  }

  /**
   * Get params
   * @return params
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getParams() {
    return params;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParams(@jakarta.annotation.Nullable Map<String, Object> params) {
    this.params = params;
  }

  public RetentionRule tagSelectors(@jakarta.annotation.Nullable List<RetentionSelector> tagSelectors) {
    
    this.tagSelectors = tagSelectors;
    return this;
  }

  public RetentionRule addTagSelectorsItem(RetentionSelector tagSelectorsItem) {
    if (this.tagSelectors == null) {
      this.tagSelectors = new ArrayList<>();
    }
    this.tagSelectors.add(tagSelectorsItem);
    return this;
  }

  /**
   * Get tagSelectors
   * @return tagSelectors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG_SELECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RetentionSelector> getTagSelectors() {
    return tagSelectors;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG_SELECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagSelectors(@jakarta.annotation.Nullable List<RetentionSelector> tagSelectors) {
    this.tagSelectors = tagSelectors;
  }

  public RetentionRule scopeSelectors(@jakarta.annotation.Nullable Map<String, List<RetentionSelector>> scopeSelectors) {
    
    this.scopeSelectors = scopeSelectors;
    return this;
  }

  public RetentionRule putScopeSelectorsItem(String key, List<RetentionSelector> scopeSelectorsItem) {
    if (this.scopeSelectors == null) {
      this.scopeSelectors = new HashMap<>();
    }
    this.scopeSelectors.put(key, scopeSelectorsItem);
    return this;
  }

  /**
   * Get scopeSelectors
   * @return scopeSelectors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE_SELECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<RetentionSelector>> getScopeSelectors() {
    return scopeSelectors;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE_SELECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScopeSelectors(@jakarta.annotation.Nullable Map<String, List<RetentionSelector>> scopeSelectors) {
    this.scopeSelectors = scopeSelectors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetentionRule retentionRule = (RetentionRule) o;
    return Objects.equals(this.id, retentionRule.id) &&
        Objects.equals(this.priority, retentionRule.priority) &&
        Objects.equals(this.disabled, retentionRule.disabled) &&
        Objects.equals(this.action, retentionRule.action) &&
        Objects.equals(this.template, retentionRule.template) &&
        Objects.equals(this.params, retentionRule.params) &&
        Objects.equals(this.tagSelectors, retentionRule.tagSelectors) &&
        Objects.equals(this.scopeSelectors, retentionRule.scopeSelectors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, priority, disabled, action, template, params, tagSelectors, scopeSelectors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetentionRule {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    tagSelectors: ").append(toIndentedString(tagSelectors)).append("\n");
    sb.append("    scopeSelectors: ").append(toIndentedString(scopeSelectors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RetentionRule instance;

    public Builder() {
      this(new RetentionRule());
    }

    protected Builder(RetentionRule instance) {
      this.instance = instance;
    }

    public RetentionRule.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public RetentionRule.Builder priority(Integer priority) {
      this.instance.priority = priority;
      return this;
    }
    public RetentionRule.Builder disabled(Boolean disabled) {
      this.instance.disabled = disabled;
      return this;
    }
    public RetentionRule.Builder action(String action) {
      this.instance.action = action;
      return this;
    }
    public RetentionRule.Builder template(String template) {
      this.instance.template = template;
      return this;
    }
    public RetentionRule.Builder params(Map<String, Object> params) {
      this.instance.params = params;
      return this;
    }
    public RetentionRule.Builder tagSelectors(List<RetentionSelector> tagSelectors) {
      this.instance.tagSelectors = tagSelectors;
      return this;
    }
    public RetentionRule.Builder scopeSelectors(Map<String, List<RetentionSelector>> scopeSelectors) {
      this.instance.scopeSelectors = scopeSelectors;
      return this;
    }


    /**
    * returns a built RetentionRule instance.
    *
    * The builder is not reusable.
    */
    public RetentionRule build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RetentionRule.Builder builder() {
    return new RetentionRule.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RetentionRule.Builder toBuilder() {
    return new RetentionRule.Builder()
      .id(getId())
      .priority(getPriority())
      .disabled(getDisabled())
      .action(getAction())
      .template(getTemplate())
      .params(getParams())
      .tagSelectors(getTagSelectors())
      .scopeSelectors(getScopeSelectors());
  }


}

