/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.Access;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RobotPermission
 */
@JsonPropertyOrder({
  RobotPermission.JSON_PROPERTY_KIND,
  RobotPermission.JSON_PROPERTY_NAMESPACE,
  RobotPermission.JSON_PROPERTY_ACCESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RobotPermission {
  public static final String JSON_PROPERTY_KIND = "kind";
  @jakarta.annotation.Nullable
  private String kind;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  @jakarta.annotation.Nullable
  private String namespace;

  public static final String JSON_PROPERTY_ACCESS = "access";
  @jakarta.annotation.Nullable
  private List<Access> access = new ArrayList<>();

  public RobotPermission() {
  }

  public RobotPermission kind(@jakarta.annotation.Nullable String kind) {
    
    this.kind = kind;
    return this;
  }

  /**
   * The kind of the permission
   * @return kind
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@jakarta.annotation.Nullable String kind) {
    this.kind = kind;
  }

  public RobotPermission namespace(@jakarta.annotation.Nullable String namespace) {
    
    this.namespace = namespace;
    return this;
  }

  /**
   * The namespace of the permission
   * @return namespace
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamespace(@jakarta.annotation.Nullable String namespace) {
    this.namespace = namespace;
  }

  public RobotPermission access(@jakarta.annotation.Nullable List<Access> access) {
    
    this.access = access;
    return this;
  }

  public RobotPermission addAccessItem(Access accessItem) {
    if (this.access == null) {
      this.access = new ArrayList<>();
    }
    this.access.add(accessItem);
    return this;
  }

  /**
   * Get access
   * @return access
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Access> getAccess() {
    return access;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccess(@jakarta.annotation.Nullable List<Access> access) {
    this.access = access;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RobotPermission robotPermission = (RobotPermission) o;
    return Objects.equals(this.kind, robotPermission.kind) &&
        Objects.equals(this.namespace, robotPermission.namespace) &&
        Objects.equals(this.access, robotPermission.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, namespace, access);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RobotPermission {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RobotPermission instance;

    public Builder() {
      this(new RobotPermission());
    }

    protected Builder(RobotPermission instance) {
      this.instance = instance;
    }

    public RobotPermission.Builder kind(String kind) {
      this.instance.kind = kind;
      return this;
    }
    public RobotPermission.Builder namespace(String namespace) {
      this.instance.namespace = namespace;
      return this;
    }
    public RobotPermission.Builder access(List<Access> access) {
      this.instance.access = access;
      return this;
    }


    /**
    * returns a built RobotPermission instance.
    *
    * The builder is not reusable.
    */
    public RobotPermission build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RobotPermission.Builder builder() {
    return new RobotPermission.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RobotPermission.Builder toBuilder() {
    return new RobotPermission.Builder()
      .kind(getKind())
      .namespace(getNamespace())
      .access(getAccess());
  }


}

