/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The response for robot account creation.
 */
@JsonPropertyOrder({
  RobotCreated.JSON_PROPERTY_ID,
  RobotCreated.JSON_PROPERTY_NAME,
  RobotCreated.JSON_PROPERTY_SECRET,
  RobotCreated.JSON_PROPERTY_CREATION_TIME,
  RobotCreated.JSON_PROPERTY_EXPIRES_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RobotCreated {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @jakarta.annotation.Nullable
  private String secret;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @jakarta.annotation.Nullable
  private Date creationTime;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @jakarta.annotation.Nullable
  private Long expiresAt;

  public RobotCreated() {
  }

  public RobotCreated id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The ID of the robot
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public RobotCreated name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the robot
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public RobotCreated secret(@jakarta.annotation.Nullable String secret) {
    
    this.secret = secret;
    return this;
  }

  /**
   * The secret of the robot
   * @return secret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecret() {
    return secret;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(@jakarta.annotation.Nullable String secret) {
    this.secret = secret;
  }

  public RobotCreated creationTime(@jakarta.annotation.Nullable Date creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

  /**
   * The creation time of the robot.
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Date creationTime) {
    this.creationTime = creationTime;
  }

  public RobotCreated expiresAt(@jakarta.annotation.Nullable Long expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * The expiration date of the robot
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable Long expiresAt) {
    this.expiresAt = expiresAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RobotCreated robotCreated = (RobotCreated) o;
    return Objects.equals(this.id, robotCreated.id) &&
        Objects.equals(this.name, robotCreated.name) &&
        Objects.equals(this.secret, robotCreated.secret) &&
        Objects.equals(this.creationTime, robotCreated.creationTime) &&
        Objects.equals(this.expiresAt, robotCreated.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, secret, creationTime, expiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RobotCreated {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RobotCreated instance;

    public Builder() {
      this(new RobotCreated());
    }

    protected Builder(RobotCreated instance) {
      this.instance = instance;
    }

    public RobotCreated.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public RobotCreated.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public RobotCreated.Builder secret(String secret) {
      this.instance.secret = secret;
      return this;
    }
    public RobotCreated.Builder creationTime(Date creationTime) {
      this.instance.creationTime = creationTime;
      return this;
    }
    public RobotCreated.Builder expiresAt(Long expiresAt) {
      this.instance.expiresAt = expiresAt;
      return this;
    }


    /**
    * returns a built RobotCreated instance.
    *
    * The builder is not reusable.
    */
    public RobotCreated build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RobotCreated.Builder builder() {
    return new RobotCreated.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RobotCreated.Builder toBuilder() {
    return new RobotCreated.Builder()
      .id(getId())
      .name(getName())
      .secret(getSecret())
      .creationTime(getCreationTime())
      .expiresAt(getExpiresAt());
  }


}

