/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.Access;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RobotCreateV1
 */
@JsonPropertyOrder({
  RobotCreateV1.JSON_PROPERTY_NAME,
  RobotCreateV1.JSON_PROPERTY_DESCRIPTION,
  RobotCreateV1.JSON_PROPERTY_EXPIRES_AT,
  RobotCreateV1.JSON_PROPERTY_ACCESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RobotCreateV1 {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @jakarta.annotation.Nullable
  private Integer expiresAt;

  public static final String JSON_PROPERTY_ACCESS = "access";
  @jakarta.annotation.Nullable
  private List<Access> access = new ArrayList<>();

  public RobotCreateV1() {
  }

  public RobotCreateV1 name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of robot account
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public RobotCreateV1 description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of robot account
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public RobotCreateV1 expiresAt(@jakarta.annotation.Nullable Integer expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * The expiration time on or after which the JWT MUST NOT be accepted for processing.
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable Integer expiresAt) {
    this.expiresAt = expiresAt;
  }

  public RobotCreateV1 access(@jakarta.annotation.Nullable List<Access> access) {
    
    this.access = access;
    return this;
  }

  public RobotCreateV1 addAccessItem(Access accessItem) {
    if (this.access == null) {
      this.access = new ArrayList<>();
    }
    this.access.add(accessItem);
    return this;
  }

  /**
   * The permission of robot account
   * @return access
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Access> getAccess() {
    return access;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccess(@jakarta.annotation.Nullable List<Access> access) {
    this.access = access;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RobotCreateV1 robotCreateV1 = (RobotCreateV1) o;
    return Objects.equals(this.name, robotCreateV1.name) &&
        Objects.equals(this.description, robotCreateV1.description) &&
        Objects.equals(this.expiresAt, robotCreateV1.expiresAt) &&
        Objects.equals(this.access, robotCreateV1.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, expiresAt, access);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RobotCreateV1 {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RobotCreateV1 instance;

    public Builder() {
      this(new RobotCreateV1());
    }

    protected Builder(RobotCreateV1 instance) {
      this.instance = instance;
    }

    public RobotCreateV1.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public RobotCreateV1.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public RobotCreateV1.Builder expiresAt(Integer expiresAt) {
      this.instance.expiresAt = expiresAt;
      return this;
    }
    public RobotCreateV1.Builder access(List<Access> access) {
      this.instance.access = access;
      return this;
    }


    /**
    * returns a built RobotCreateV1 instance.
    *
    * The builder is not reusable.
    */
    public RobotCreateV1 build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RobotCreateV1.Builder builder() {
    return new RobotCreateV1.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RobotCreateV1.Builder toBuilder() {
    return new RobotCreateV1.Builder()
      .name(getName())
      .description(getDescription())
      .expiresAt(getExpiresAt())
      .access(getAccess());
  }


}

