/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.RobotPermission;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Robot
 */
@JsonPropertyOrder({
  Robot.JSON_PROPERTY_ID,
  Robot.JSON_PROPERTY_NAME,
  Robot.JSON_PROPERTY_DESCRIPTION,
  Robot.JSON_PROPERTY_SECRET,
  Robot.JSON_PROPERTY_LEVEL,
  Robot.JSON_PROPERTY_DURATION,
  Robot.JSON_PROPERTY_EDITABLE,
  Robot.JSON_PROPERTY_DISABLE,
  Robot.JSON_PROPERTY_EXPIRES_AT,
  Robot.JSON_PROPERTY_PERMISSIONS,
  Robot.JSON_PROPERTY_CREATOR_TYPE,
  Robot.JSON_PROPERTY_CREATOR_REF,
  Robot.JSON_PROPERTY_CREATION_TIME,
  Robot.JSON_PROPERTY_UPDATE_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Robot {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @jakarta.annotation.Nullable
  private String secret;

  public static final String JSON_PROPERTY_LEVEL = "level";
  @jakarta.annotation.Nullable
  private String level;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private JsonNullable<Long> duration = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_EDITABLE = "editable";
  @jakarta.annotation.Nullable
  private Boolean editable;

  public static final String JSON_PROPERTY_DISABLE = "disable";
  @jakarta.annotation.Nullable
  private Boolean disable;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @jakarta.annotation.Nullable
  private Long expiresAt;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @jakarta.annotation.Nullable
  private List<RobotPermission> permissions = new ArrayList<>();

  public static final String JSON_PROPERTY_CREATOR_TYPE = "creator_type";
  @jakarta.annotation.Nullable
  private String creatorType;

  public static final String JSON_PROPERTY_CREATOR_REF = "creator_ref";
  @jakarta.annotation.Nullable
  private Integer creatorRef;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @jakarta.annotation.Nullable
  private Date creationTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  @jakarta.annotation.Nullable
  private Date updateTime;

  public Robot() {
  }

  public Robot id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The ID of the robot
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public Robot name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the robot
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Robot description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of the robot
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public Robot secret(@jakarta.annotation.Nullable String secret) {
    
    this.secret = secret;
    return this;
  }

  /**
   * The secret of the robot
   * @return secret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecret() {
    return secret;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(@jakarta.annotation.Nullable String secret) {
    this.secret = secret;
  }

  public Robot level(@jakarta.annotation.Nullable String level) {
    
    this.level = level;
    return this;
  }

  /**
   * The level of the robot, project or system
   * @return level
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLevel() {
    return level;
  }


  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel(@jakarta.annotation.Nullable String level) {
    this.level = level;
  }

  public Robot duration(@jakarta.annotation.Nullable Long duration) {
    this.duration = JsonNullable.<Long>of(duration);
    
    return this;
  }

  /**
   * The duration of the robot in days, duration must be either -1(Never) or a positive integer
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getDuration() {
        return duration.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getDuration_JsonNullable() {
    return duration;
  }
  
  @JsonProperty(JSON_PROPERTY_DURATION)
  public void setDuration_JsonNullable(JsonNullable<Long> duration) {
    this.duration = duration;
  }

  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = JsonNullable.<Long>of(duration);
  }

  public Robot editable(@jakarta.annotation.Nullable Boolean editable) {
    
    this.editable = editable;
    return this;
  }

  /**
   * The editable status of the robot
   * @return editable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EDITABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEditable() {
    return editable;
  }


  @JsonProperty(value = JSON_PROPERTY_EDITABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditable(@jakarta.annotation.Nullable Boolean editable) {
    this.editable = editable;
  }

  public Robot disable(@jakarta.annotation.Nullable Boolean disable) {
    
    this.disable = disable;
    return this;
  }

  /**
   * The disable status of the robot
   * @return disable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisable() {
    return disable;
  }


  @JsonProperty(value = JSON_PROPERTY_DISABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisable(@jakarta.annotation.Nullable Boolean disable) {
    this.disable = disable;
  }

  public Robot expiresAt(@jakarta.annotation.Nullable Long expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * The expiration date of the robot
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable Long expiresAt) {
    this.expiresAt = expiresAt;
  }

  public Robot permissions(@jakarta.annotation.Nullable List<RobotPermission> permissions) {
    
    this.permissions = permissions;
    return this;
  }

  public Robot addPermissionsItem(RobotPermission permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RobotPermission> getPermissions() {
    return permissions;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@jakarta.annotation.Nullable List<RobotPermission> permissions) {
    this.permissions = permissions;
  }

  public Robot creatorType(@jakarta.annotation.Nullable String creatorType) {
    
    this.creatorType = creatorType;
    return this;
  }

  /**
   * The type of the robot creator, like local(harbor_user) or robot.
   * @return creatorType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATOR_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatorType() {
    return creatorType;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATOR_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatorType(@jakarta.annotation.Nullable String creatorType) {
    this.creatorType = creatorType;
  }

  public Robot creatorRef(@jakarta.annotation.Nullable Integer creatorRef) {
    
    this.creatorRef = creatorRef;
    return this;
  }

  /**
   * The reference of the robot creator, like the id of harbor user.
   * @return creatorRef
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATOR_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCreatorRef() {
    return creatorRef;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATOR_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatorRef(@jakarta.annotation.Nullable Integer creatorRef) {
    this.creatorRef = creatorRef;
  }

  public Robot creationTime(@jakarta.annotation.Nullable Date creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

  /**
   * The creation time of the robot.
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Date creationTime) {
    this.creationTime = creationTime;
  }

  public Robot updateTime(@jakarta.annotation.Nullable Date updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

  /**
   * The update time of the robot.
   * @return updateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(@jakarta.annotation.Nullable Date updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Robot robot = (Robot) o;
    return Objects.equals(this.id, robot.id) &&
        Objects.equals(this.name, robot.name) &&
        Objects.equals(this.description, robot.description) &&
        Objects.equals(this.secret, robot.secret) &&
        Objects.equals(this.level, robot.level) &&
        equalsNullable(this.duration, robot.duration) &&
        Objects.equals(this.editable, robot.editable) &&
        Objects.equals(this.disable, robot.disable) &&
        Objects.equals(this.expiresAt, robot.expiresAt) &&
        Objects.equals(this.permissions, robot.permissions) &&
        Objects.equals(this.creatorType, robot.creatorType) &&
        Objects.equals(this.creatorRef, robot.creatorRef) &&
        Objects.equals(this.creationTime, robot.creationTime) &&
        Objects.equals(this.updateTime, robot.updateTime);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, secret, level, hashCodeNullable(duration), editable, disable, expiresAt, permissions, creatorType, creatorRef, creationTime, updateTime);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Robot {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    disable: ").append(toIndentedString(disable)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    creatorType: ").append(toIndentedString(creatorType)).append("\n");
    sb.append("    creatorRef: ").append(toIndentedString(creatorRef)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Robot instance;

    public Builder() {
      this(new Robot());
    }

    protected Builder(Robot instance) {
      this.instance = instance;
    }

    public Robot.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public Robot.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public Robot.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public Robot.Builder secret(String secret) {
      this.instance.secret = secret;
      return this;
    }
    public Robot.Builder level(String level) {
      this.instance.level = level;
      return this;
    }
    public Robot.Builder duration(Long duration) {
      this.instance.duration = JsonNullable.<Long>of(duration);
      return this;
    }
    public Robot.Builder duration(JsonNullable<Long> duration) {
      this.instance.duration = duration;
      return this;
    }
    public Robot.Builder editable(Boolean editable) {
      this.instance.editable = editable;
      return this;
    }
    public Robot.Builder disable(Boolean disable) {
      this.instance.disable = disable;
      return this;
    }
    public Robot.Builder expiresAt(Long expiresAt) {
      this.instance.expiresAt = expiresAt;
      return this;
    }
    public Robot.Builder permissions(List<RobotPermission> permissions) {
      this.instance.permissions = permissions;
      return this;
    }
    public Robot.Builder creatorType(String creatorType) {
      this.instance.creatorType = creatorType;
      return this;
    }
    public Robot.Builder creatorRef(Integer creatorRef) {
      this.instance.creatorRef = creatorRef;
      return this;
    }
    public Robot.Builder creationTime(Date creationTime) {
      this.instance.creationTime = creationTime;
      return this;
    }
    public Robot.Builder updateTime(Date updateTime) {
      this.instance.updateTime = updateTime;
      return this;
    }


    /**
    * returns a built Robot instance.
    *
    * The builder is not reusable.
    */
    public Robot build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Robot.Builder builder() {
    return new Robot.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Robot.Builder toBuilder() {
    return new Robot.Builder()
      .id(getId())
      .name(getName())
      .description(getDescription())
      .secret(getSecret())
      .level(getLevel())
      .duration(getDuration())
      .editable(getEditable())
      .disable(getDisable())
      .expiresAt(getExpiresAt())
      .permissions(getPermissions())
      .creatorType(getCreatorType())
      .creatorRef(getCreatorRef())
      .creationTime(getCreationTime())
      .updateTime(getUpdateTime());
  }


}

