/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RoleRequest
 */
@JsonPropertyOrder({
  RoleRequest.JSON_PROPERTY_ROLE_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RoleRequest {
  public static final String JSON_PROPERTY_ROLE_ID = "role_id";
  @jakarta.annotation.Nullable
  private Integer roleId;

  public RoleRequest() {
  }

  public RoleRequest roleId(@jakarta.annotation.Nullable Integer roleId) {
    
    this.roleId = roleId;
    return this;
  }

  /**
   * The role id 1 for projectAdmin, 2 for developer, 3 for guest, 4 for maintainer
   * @return roleId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRoleId() {
    return roleId;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoleId(@jakarta.annotation.Nullable Integer roleId) {
    this.roleId = roleId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleRequest roleRequest = (RoleRequest) o;
    return Objects.equals(this.roleId, roleRequest.roleId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roleId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleRequest {\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private RoleRequest instance;

    public Builder() {
      this(new RoleRequest());
    }

    protected Builder(RoleRequest instance) {
      this.instance = instance;
    }

    public RoleRequest.Builder roleId(Integer roleId) {
      this.instance.roleId = roleId;
      return this;
    }


    /**
    * returns a built RoleRequest instance.
    *
    * The builder is not reusable.
    */
    public RoleRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RoleRequest.Builder builder() {
    return new RoleRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RoleRequest.Builder toBuilder() {
    return new RoleRequest.Builder()
      .roleId(getRoleId());
  }


}

