/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.Scanner;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The generate SBOM overview information
 */
@JsonPropertyOrder({
  SBOMOverview.JSON_PROPERTY_START_TIME,
  SBOMOverview.JSON_PROPERTY_END_TIME,
  SBOMOverview.JSON_PROPERTY_SCAN_STATUS,
  SBOMOverview.JSON_PROPERTY_SBOM_DIGEST,
  SBOMOverview.JSON_PROPERTY_REPORT_ID,
  SBOMOverview.JSON_PROPERTY_DURATION,
  SBOMOverview.JSON_PROPERTY_SCANNER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SBOMOverview {
  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Date startTime;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  @jakarta.annotation.Nullable
  private Date endTime;

  public static final String JSON_PROPERTY_SCAN_STATUS = "scan_status";
  @jakarta.annotation.Nullable
  private String scanStatus;

  public static final String JSON_PROPERTY_SBOM_DIGEST = "sbom_digest";
  @jakarta.annotation.Nullable
  private String sbomDigest;

  public static final String JSON_PROPERTY_REPORT_ID = "report_id";
  @jakarta.annotation.Nullable
  private String reportId;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Long duration;

  public static final String JSON_PROPERTY_SCANNER = "scanner";
  @jakarta.annotation.Nullable
  private Scanner scanner;

  public SBOMOverview() {
  }

  public SBOMOverview startTime(@jakarta.annotation.Nullable Date startTime) {
    
    this.startTime = startTime;
    return this;
  }

  /**
   * The start time of the generating sbom report task
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getStartTime() {
    return startTime;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Date startTime) {
    this.startTime = startTime;
  }

  public SBOMOverview endTime(@jakarta.annotation.Nullable Date endTime) {
    
    this.endTime = endTime;
    return this;
  }

  /**
   * The end time of the generating sbom report task
   * @return endTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getEndTime() {
    return endTime;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@jakarta.annotation.Nullable Date endTime) {
    this.endTime = endTime;
  }

  public SBOMOverview scanStatus(@jakarta.annotation.Nullable String scanStatus) {
    
    this.scanStatus = scanStatus;
    return this;
  }

  /**
   * The status of the generating SBOM task
   * @return scanStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCAN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScanStatus() {
    return scanStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_SCAN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScanStatus(@jakarta.annotation.Nullable String scanStatus) {
    this.scanStatus = scanStatus;
  }

  public SBOMOverview sbomDigest(@jakarta.annotation.Nullable String sbomDigest) {
    
    this.sbomDigest = sbomDigest;
    return this;
  }

  /**
   * The digest of the generated SBOM accessory
   * @return sbomDigest
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SBOM_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSbomDigest() {
    return sbomDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_SBOM_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSbomDigest(@jakarta.annotation.Nullable String sbomDigest) {
    this.sbomDigest = sbomDigest;
  }

  public SBOMOverview reportId(@jakarta.annotation.Nullable String reportId) {
    
    this.reportId = reportId;
    return this;
  }

  /**
   * id of the native scan report
   * @return reportId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPORT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportId() {
    return reportId;
  }


  @JsonProperty(value = JSON_PROPERTY_REPORT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportId(@jakarta.annotation.Nullable String reportId) {
    this.reportId = reportId;
  }

  public SBOMOverview duration(@jakarta.annotation.Nullable Long duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * Time in seconds required to create the report
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
  }

  public SBOMOverview scanner(@jakarta.annotation.Nullable Scanner scanner) {
    
    this.scanner = scanner;
    return this;
  }

  /**
   * Get scanner
   * @return scanner
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCANNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Scanner getScanner() {
    return scanner;
  }


  @JsonProperty(value = JSON_PROPERTY_SCANNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScanner(@jakarta.annotation.Nullable Scanner scanner) {
    this.scanner = scanner;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SBOMOverview sbOMOverview = (SBOMOverview) o;
    return Objects.equals(this.startTime, sbOMOverview.startTime) &&
        Objects.equals(this.endTime, sbOMOverview.endTime) &&
        Objects.equals(this.scanStatus, sbOMOverview.scanStatus) &&
        Objects.equals(this.sbomDigest, sbOMOverview.sbomDigest) &&
        Objects.equals(this.reportId, sbOMOverview.reportId) &&
        Objects.equals(this.duration, sbOMOverview.duration) &&
        Objects.equals(this.scanner, sbOMOverview.scanner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startTime, endTime, scanStatus, sbomDigest, reportId, duration, scanner);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SBOMOverview {\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    scanStatus: ").append(toIndentedString(scanStatus)).append("\n");
    sb.append("    sbomDigest: ").append(toIndentedString(sbomDigest)).append("\n");
    sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    scanner: ").append(toIndentedString(scanner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SBOMOverview instance;

    public Builder() {
      this(new SBOMOverview());
    }

    protected Builder(SBOMOverview instance) {
      this.instance = instance;
    }

    public SBOMOverview.Builder startTime(Date startTime) {
      this.instance.startTime = startTime;
      return this;
    }
    public SBOMOverview.Builder endTime(Date endTime) {
      this.instance.endTime = endTime;
      return this;
    }
    public SBOMOverview.Builder scanStatus(String scanStatus) {
      this.instance.scanStatus = scanStatus;
      return this;
    }
    public SBOMOverview.Builder sbomDigest(String sbomDigest) {
      this.instance.sbomDigest = sbomDigest;
      return this;
    }
    public SBOMOverview.Builder reportId(String reportId) {
      this.instance.reportId = reportId;
      return this;
    }
    public SBOMOverview.Builder duration(Long duration) {
      this.instance.duration = duration;
      return this;
    }
    public SBOMOverview.Builder scanner(Scanner scanner) {
      this.instance.scanner = scanner;
      return this;
    }


    /**
    * returns a built SBOMOverview instance.
    *
    * The builder is not reusable.
    */
    public SBOMOverview build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SBOMOverview.Builder builder() {
    return new SBOMOverview.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SBOMOverview.Builder toBuilder() {
    return new SBOMOverview.Builder()
      .startTime(getStartTime())
      .endTime(getEndTime())
      .scanStatus(getScanStatus())
      .sbomDigest(getSbomDigest())
      .reportId(getReportId())
      .duration(getDuration())
      .scanner(getScanner());
  }


}

