/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ScanType
 */
@JsonPropertyOrder({
  ScanType.JSON_PROPERTY_SCAN_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ScanType {
  /**
   * The scan type for the scan request. Two options are currently supported, vulnerability and sbom
   */
  public enum ScanTypeEnum {
    VULNERABILITY(String.valueOf("vulnerability")),
    
    SBOM(String.valueOf("sbom"));

    private String value;

    ScanTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ScanTypeEnum fromValue(String value) {
      for (ScanTypeEnum b : ScanTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SCAN_TYPE = "scan_type";
  @jakarta.annotation.Nullable
  private ScanTypeEnum scanType;

  public ScanType() {
  }

  public ScanType scanType(@jakarta.annotation.Nullable ScanTypeEnum scanType) {
    
    this.scanType = scanType;
    return this;
  }

  /**
   * The scan type for the scan request. Two options are currently supported, vulnerability and sbom
   * @return scanType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCAN_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ScanTypeEnum getScanType() {
    return scanType;
  }


  @JsonProperty(value = JSON_PROPERTY_SCAN_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScanType(@jakarta.annotation.Nullable ScanTypeEnum scanType) {
    this.scanType = scanType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanType scanType = (ScanType) o;
    return Objects.equals(this.scanType, scanType.scanType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scanType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanType {\n");
    sb.append("    scanType: ").append(toIndentedString(scanType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ScanType instance;

    public Builder() {
      this(new ScanType());
    }

    protected Builder(ScanType instance) {
      this.instance = instance;
    }

    public ScanType.Builder scanType(ScanTypeEnum scanType) {
      this.instance.scanType = scanType;
      return this;
    }


    /**
    * returns a built ScanType instance.
    *
    * The builder is not reusable.
    */
    public ScanType build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ScanType.Builder builder() {
    return new ScanType.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ScanType.Builder toBuilder() {
    return new ScanType.Builder()
      .scanType(getScanType());
  }


}

