/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SearchRepository
 */
@JsonPropertyOrder({
  SearchRepository.JSON_PROPERTY_PROJECT_ID,
  SearchRepository.JSON_PROPERTY_PROJECT_NAME,
  SearchRepository.JSON_PROPERTY_PROJECT_PUBLIC,
  SearchRepository.JSON_PROPERTY_REPOSITORY_NAME,
  SearchRepository.JSON_PROPERTY_PULL_COUNT,
  SearchRepository.JSON_PROPERTY_ARTIFACT_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SearchRepository {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_PROJECT_NAME = "project_name";
  @jakarta.annotation.Nullable
  private String projectName;

  public static final String JSON_PROPERTY_PROJECT_PUBLIC = "project_public";
  @jakarta.annotation.Nullable
  private Boolean projectPublic;

  public static final String JSON_PROPERTY_REPOSITORY_NAME = "repository_name";
  @jakarta.annotation.Nullable
  private String repositoryName;

  public static final String JSON_PROPERTY_PULL_COUNT = "pull_count";
  @jakarta.annotation.Nullable
  private Integer pullCount;

  public static final String JSON_PROPERTY_ARTIFACT_COUNT = "artifact_count";
  @jakarta.annotation.Nullable
  private Integer artifactCount;

  public SearchRepository() {
  }

  public SearchRepository projectId(@jakarta.annotation.Nullable Integer projectId) {
    
    this.projectId = projectId;
    return this;
  }

  /**
   * The ID of the project that the repository belongs to
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }

  public SearchRepository projectName(@jakarta.annotation.Nullable String projectName) {
    
    this.projectName = projectName;
    return this;
  }

  /**
   * The name of the project that the repository belongs to
   * @return projectName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectName() {
    return projectName;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectName(@jakarta.annotation.Nullable String projectName) {
    this.projectName = projectName;
  }

  public SearchRepository projectPublic(@jakarta.annotation.Nullable Boolean projectPublic) {
    
    this.projectPublic = projectPublic;
    return this;
  }

  /**
   * The flag to indicate the publicity of the project that the repository belongs to (1 is public, 0 is not)
   * @return projectPublic
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_PUBLIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getProjectPublic() {
    return projectPublic;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_PUBLIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectPublic(@jakarta.annotation.Nullable Boolean projectPublic) {
    this.projectPublic = projectPublic;
  }

  public SearchRepository repositoryName(@jakarta.annotation.Nullable String repositoryName) {
    
    this.repositoryName = repositoryName;
    return this;
  }

  /**
   * The name of the repository
   * @return repositoryName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPOSITORY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRepositoryName() {
    return repositoryName;
  }


  @JsonProperty(value = JSON_PROPERTY_REPOSITORY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepositoryName(@jakarta.annotation.Nullable String repositoryName) {
    this.repositoryName = repositoryName;
  }

  public SearchRepository pullCount(@jakarta.annotation.Nullable Integer pullCount) {
    
    this.pullCount = pullCount;
    return this;
  }

  /**
   * The count how many times the repository is pulled
   * @return pullCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PULL_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPullCount() {
    return pullCount;
  }


  @JsonProperty(value = JSON_PROPERTY_PULL_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPullCount(@jakarta.annotation.Nullable Integer pullCount) {
    this.pullCount = pullCount;
  }

  public SearchRepository artifactCount(@jakarta.annotation.Nullable Integer artifactCount) {
    
    this.artifactCount = artifactCount;
    return this;
  }

  /**
   * The count of artifacts in the repository
   * @return artifactCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getArtifactCount() {
    return artifactCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArtifactCount(@jakarta.annotation.Nullable Integer artifactCount) {
    this.artifactCount = artifactCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRepository searchRepository = (SearchRepository) o;
    return Objects.equals(this.projectId, searchRepository.projectId) &&
        Objects.equals(this.projectName, searchRepository.projectName) &&
        Objects.equals(this.projectPublic, searchRepository.projectPublic) &&
        Objects.equals(this.repositoryName, searchRepository.repositoryName) &&
        Objects.equals(this.pullCount, searchRepository.pullCount) &&
        Objects.equals(this.artifactCount, searchRepository.artifactCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, projectName, projectPublic, repositoryName, pullCount, artifactCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRepository {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    projectPublic: ").append(toIndentedString(projectPublic)).append("\n");
    sb.append("    repositoryName: ").append(toIndentedString(repositoryName)).append("\n");
    sb.append("    pullCount: ").append(toIndentedString(pullCount)).append("\n");
    sb.append("    artifactCount: ").append(toIndentedString(artifactCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SearchRepository instance;

    public Builder() {
      this(new SearchRepository());
    }

    protected Builder(SearchRepository instance) {
      this.instance = instance;
    }

    public SearchRepository.Builder projectId(Integer projectId) {
      this.instance.projectId = projectId;
      return this;
    }
    public SearchRepository.Builder projectName(String projectName) {
      this.instance.projectName = projectName;
      return this;
    }
    public SearchRepository.Builder projectPublic(Boolean projectPublic) {
      this.instance.projectPublic = projectPublic;
      return this;
    }
    public SearchRepository.Builder repositoryName(String repositoryName) {
      this.instance.repositoryName = repositoryName;
      return this;
    }
    public SearchRepository.Builder pullCount(Integer pullCount) {
      this.instance.pullCount = pullCount;
      return this;
    }
    public SearchRepository.Builder artifactCount(Integer artifactCount) {
      this.instance.artifactCount = artifactCount;
      return this;
    }


    /**
    * returns a built SearchRepository instance.
    *
    * The builder is not reusable.
    */
    public SearchRepository build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SearchRepository.Builder builder() {
    return new SearchRepository.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SearchRepository.Builder toBuilder() {
    return new SearchRepository.Builder()
      .projectId(getProjectId())
      .projectName(getProjectName())
      .projectPublic(getProjectPublic())
      .repositoryName(getRepositoryName())
      .pullCount(getPullCount())
      .artifactCount(getArtifactCount());
  }


}

