/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.DangerousArtifact;
import com.ryan.openapi.harbor.client.model.DangerousCVE;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * the security summary
 */
@JsonPropertyOrder({
  SecuritySummary.JSON_PROPERTY_CRITICAL_CNT,
  SecuritySummary.JSON_PROPERTY_HIGH_CNT,
  SecuritySummary.JSON_PROPERTY_MEDIUM_CNT,
  SecuritySummary.JSON_PROPERTY_LOW_CNT,
  SecuritySummary.JSON_PROPERTY_NONE_CNT,
  SecuritySummary.JSON_PROPERTY_UNKNOWN_CNT,
  SecuritySummary.JSON_PROPERTY_TOTAL_VULS,
  SecuritySummary.JSON_PROPERTY_SCANNED_CNT,
  SecuritySummary.JSON_PROPERTY_TOTAL_ARTIFACT,
  SecuritySummary.JSON_PROPERTY_FIXABLE_CNT,
  SecuritySummary.JSON_PROPERTY_DANGEROUS_CVES,
  SecuritySummary.JSON_PROPERTY_DANGEROUS_ARTIFACTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SecuritySummary {
  public static final String JSON_PROPERTY_CRITICAL_CNT = "critical_cnt";
  @jakarta.annotation.Nullable
  private Long criticalCnt;

  public static final String JSON_PROPERTY_HIGH_CNT = "high_cnt";
  @jakarta.annotation.Nullable
  private Long highCnt;

  public static final String JSON_PROPERTY_MEDIUM_CNT = "medium_cnt";
  @jakarta.annotation.Nullable
  private Long mediumCnt;

  public static final String JSON_PROPERTY_LOW_CNT = "low_cnt";
  @jakarta.annotation.Nullable
  private Long lowCnt;

  public static final String JSON_PROPERTY_NONE_CNT = "none_cnt";
  @jakarta.annotation.Nullable
  private Long noneCnt;

  public static final String JSON_PROPERTY_UNKNOWN_CNT = "unknown_cnt";
  @jakarta.annotation.Nullable
  private Long unknownCnt;

  public static final String JSON_PROPERTY_TOTAL_VULS = "total_vuls";
  @jakarta.annotation.Nullable
  private Long totalVuls;

  public static final String JSON_PROPERTY_SCANNED_CNT = "scanned_cnt";
  @jakarta.annotation.Nullable
  private Long scannedCnt;

  public static final String JSON_PROPERTY_TOTAL_ARTIFACT = "total_artifact";
  @jakarta.annotation.Nullable
  private Long totalArtifact;

  public static final String JSON_PROPERTY_FIXABLE_CNT = "fixable_cnt";
  @jakarta.annotation.Nullable
  private Long fixableCnt;

  public static final String JSON_PROPERTY_DANGEROUS_CVES = "dangerous_cves";
  @jakarta.annotation.Nullable
  private List<DangerousCVE> dangerousCves = new ArrayList<>();

  public static final String JSON_PROPERTY_DANGEROUS_ARTIFACTS = "dangerous_artifacts";
  @jakarta.annotation.Nullable
  private List<DangerousArtifact> dangerousArtifacts = new ArrayList<>();

  public SecuritySummary() {
  }

  public SecuritySummary criticalCnt(@jakarta.annotation.Nullable Long criticalCnt) {
    
    this.criticalCnt = criticalCnt;
    return this;
  }

  /**
   * the count of critical vulnerabilities
   * @return criticalCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CRITICAL_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCriticalCnt() {
    return criticalCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_CRITICAL_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCriticalCnt(@jakarta.annotation.Nullable Long criticalCnt) {
    this.criticalCnt = criticalCnt;
  }

  public SecuritySummary highCnt(@jakarta.annotation.Nullable Long highCnt) {
    
    this.highCnt = highCnt;
    return this;
  }

  /**
   * the count of high vulnerabilities
   * @return highCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHighCnt() {
    return highCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighCnt(@jakarta.annotation.Nullable Long highCnt) {
    this.highCnt = highCnt;
  }

  public SecuritySummary mediumCnt(@jakarta.annotation.Nullable Long mediumCnt) {
    
    this.mediumCnt = mediumCnt;
    return this;
  }

  /**
   * the count of medium vulnerabilities
   * @return mediumCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEDIUM_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMediumCnt() {
    return mediumCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_MEDIUM_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMediumCnt(@jakarta.annotation.Nullable Long mediumCnt) {
    this.mediumCnt = mediumCnt;
  }

  public SecuritySummary lowCnt(@jakarta.annotation.Nullable Long lowCnt) {
    
    this.lowCnt = lowCnt;
    return this;
  }

  /**
   * the count of low vulnerabilities
   * @return lowCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOW_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLowCnt() {
    return lowCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_LOW_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLowCnt(@jakarta.annotation.Nullable Long lowCnt) {
    this.lowCnt = lowCnt;
  }

  public SecuritySummary noneCnt(@jakarta.annotation.Nullable Long noneCnt) {
    
    this.noneCnt = noneCnt;
    return this;
  }

  /**
   * the count of none vulnerabilities
   * @return noneCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NONE_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNoneCnt() {
    return noneCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_NONE_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoneCnt(@jakarta.annotation.Nullable Long noneCnt) {
    this.noneCnt = noneCnt;
  }

  public SecuritySummary unknownCnt(@jakarta.annotation.Nullable Long unknownCnt) {
    
    this.unknownCnt = unknownCnt;
    return this;
  }

  /**
   * the count of unknown vulnerabilities
   * @return unknownCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNKNOWN_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUnknownCnt() {
    return unknownCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_UNKNOWN_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnknownCnt(@jakarta.annotation.Nullable Long unknownCnt) {
    this.unknownCnt = unknownCnt;
  }

  public SecuritySummary totalVuls(@jakarta.annotation.Nullable Long totalVuls) {
    
    this.totalVuls = totalVuls;
    return this;
  }

  /**
   * the count of total vulnerabilities
   * @return totalVuls
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_VULS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalVuls() {
    return totalVuls;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_VULS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalVuls(@jakarta.annotation.Nullable Long totalVuls) {
    this.totalVuls = totalVuls;
  }

  public SecuritySummary scannedCnt(@jakarta.annotation.Nullable Long scannedCnt) {
    
    this.scannedCnt = scannedCnt;
    return this;
  }

  /**
   * the count of scanned artifacts
   * @return scannedCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCANNED_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getScannedCnt() {
    return scannedCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_SCANNED_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScannedCnt(@jakarta.annotation.Nullable Long scannedCnt) {
    this.scannedCnt = scannedCnt;
  }

  public SecuritySummary totalArtifact(@jakarta.annotation.Nullable Long totalArtifact) {
    
    this.totalArtifact = totalArtifact;
    return this;
  }

  /**
   * the total count of artifacts
   * @return totalArtifact
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ARTIFACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalArtifact() {
    return totalArtifact;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_ARTIFACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalArtifact(@jakarta.annotation.Nullable Long totalArtifact) {
    this.totalArtifact = totalArtifact;
  }

  public SecuritySummary fixableCnt(@jakarta.annotation.Nullable Long fixableCnt) {
    
    this.fixableCnt = fixableCnt;
    return this;
  }

  /**
   * the count of fixable vulnerabilities
   * @return fixableCnt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIXABLE_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFixableCnt() {
    return fixableCnt;
  }


  @JsonProperty(value = JSON_PROPERTY_FIXABLE_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFixableCnt(@jakarta.annotation.Nullable Long fixableCnt) {
    this.fixableCnt = fixableCnt;
  }

  public SecuritySummary dangerousCves(@jakarta.annotation.Nullable List<DangerousCVE> dangerousCves) {
    
    this.dangerousCves = dangerousCves;
    return this;
  }

  public SecuritySummary addDangerousCvesItem(DangerousCVE dangerousCvesItem) {
    if (this.dangerousCves == null) {
      this.dangerousCves = new ArrayList<>();
    }
    this.dangerousCves.add(dangerousCvesItem);
    return this;
  }

  /**
   * the list of dangerous CVEs
   * @return dangerousCves
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DANGEROUS_CVES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DangerousCVE> getDangerousCves() {
    return dangerousCves;
  }


  @JsonProperty(value = JSON_PROPERTY_DANGEROUS_CVES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDangerousCves(@jakarta.annotation.Nullable List<DangerousCVE> dangerousCves) {
    this.dangerousCves = dangerousCves;
  }

  public SecuritySummary dangerousArtifacts(@jakarta.annotation.Nullable List<DangerousArtifact> dangerousArtifacts) {
    
    this.dangerousArtifacts = dangerousArtifacts;
    return this;
  }

  public SecuritySummary addDangerousArtifactsItem(DangerousArtifact dangerousArtifactsItem) {
    if (this.dangerousArtifacts == null) {
      this.dangerousArtifacts = new ArrayList<>();
    }
    this.dangerousArtifacts.add(dangerousArtifactsItem);
    return this;
  }

  /**
   * the list of dangerous artifacts
   * @return dangerousArtifacts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DANGEROUS_ARTIFACTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DangerousArtifact> getDangerousArtifacts() {
    return dangerousArtifacts;
  }


  @JsonProperty(value = JSON_PROPERTY_DANGEROUS_ARTIFACTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDangerousArtifacts(@jakarta.annotation.Nullable List<DangerousArtifact> dangerousArtifacts) {
    this.dangerousArtifacts = dangerousArtifacts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecuritySummary securitySummary = (SecuritySummary) o;
    return Objects.equals(this.criticalCnt, securitySummary.criticalCnt) &&
        Objects.equals(this.highCnt, securitySummary.highCnt) &&
        Objects.equals(this.mediumCnt, securitySummary.mediumCnt) &&
        Objects.equals(this.lowCnt, securitySummary.lowCnt) &&
        Objects.equals(this.noneCnt, securitySummary.noneCnt) &&
        Objects.equals(this.unknownCnt, securitySummary.unknownCnt) &&
        Objects.equals(this.totalVuls, securitySummary.totalVuls) &&
        Objects.equals(this.scannedCnt, securitySummary.scannedCnt) &&
        Objects.equals(this.totalArtifact, securitySummary.totalArtifact) &&
        Objects.equals(this.fixableCnt, securitySummary.fixableCnt) &&
        Objects.equals(this.dangerousCves, securitySummary.dangerousCves) &&
        Objects.equals(this.dangerousArtifacts, securitySummary.dangerousArtifacts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(criticalCnt, highCnt, mediumCnt, lowCnt, noneCnt, unknownCnt, totalVuls, scannedCnt, totalArtifact, fixableCnt, dangerousCves, dangerousArtifacts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecuritySummary {\n");
    sb.append("    criticalCnt: ").append(toIndentedString(criticalCnt)).append("\n");
    sb.append("    highCnt: ").append(toIndentedString(highCnt)).append("\n");
    sb.append("    mediumCnt: ").append(toIndentedString(mediumCnt)).append("\n");
    sb.append("    lowCnt: ").append(toIndentedString(lowCnt)).append("\n");
    sb.append("    noneCnt: ").append(toIndentedString(noneCnt)).append("\n");
    sb.append("    unknownCnt: ").append(toIndentedString(unknownCnt)).append("\n");
    sb.append("    totalVuls: ").append(toIndentedString(totalVuls)).append("\n");
    sb.append("    scannedCnt: ").append(toIndentedString(scannedCnt)).append("\n");
    sb.append("    totalArtifact: ").append(toIndentedString(totalArtifact)).append("\n");
    sb.append("    fixableCnt: ").append(toIndentedString(fixableCnt)).append("\n");
    sb.append("    dangerousCves: ").append(toIndentedString(dangerousCves)).append("\n");
    sb.append("    dangerousArtifacts: ").append(toIndentedString(dangerousArtifacts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SecuritySummary instance;

    public Builder() {
      this(new SecuritySummary());
    }

    protected Builder(SecuritySummary instance) {
      this.instance = instance;
    }

    public SecuritySummary.Builder criticalCnt(Long criticalCnt) {
      this.instance.criticalCnt = criticalCnt;
      return this;
    }
    public SecuritySummary.Builder highCnt(Long highCnt) {
      this.instance.highCnt = highCnt;
      return this;
    }
    public SecuritySummary.Builder mediumCnt(Long mediumCnt) {
      this.instance.mediumCnt = mediumCnt;
      return this;
    }
    public SecuritySummary.Builder lowCnt(Long lowCnt) {
      this.instance.lowCnt = lowCnt;
      return this;
    }
    public SecuritySummary.Builder noneCnt(Long noneCnt) {
      this.instance.noneCnt = noneCnt;
      return this;
    }
    public SecuritySummary.Builder unknownCnt(Long unknownCnt) {
      this.instance.unknownCnt = unknownCnt;
      return this;
    }
    public SecuritySummary.Builder totalVuls(Long totalVuls) {
      this.instance.totalVuls = totalVuls;
      return this;
    }
    public SecuritySummary.Builder scannedCnt(Long scannedCnt) {
      this.instance.scannedCnt = scannedCnt;
      return this;
    }
    public SecuritySummary.Builder totalArtifact(Long totalArtifact) {
      this.instance.totalArtifact = totalArtifact;
      return this;
    }
    public SecuritySummary.Builder fixableCnt(Long fixableCnt) {
      this.instance.fixableCnt = fixableCnt;
      return this;
    }
    public SecuritySummary.Builder dangerousCves(List<DangerousCVE> dangerousCves) {
      this.instance.dangerousCves = dangerousCves;
      return this;
    }
    public SecuritySummary.Builder dangerousArtifacts(List<DangerousArtifact> dangerousArtifacts) {
      this.instance.dangerousArtifacts = dangerousArtifacts;
      return this;
    }


    /**
    * returns a built SecuritySummary instance.
    *
    * The builder is not reusable.
    */
    public SecuritySummary build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SecuritySummary.Builder builder() {
    return new SecuritySummary.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SecuritySummary.Builder toBuilder() {
    return new SecuritySummary.Builder()
      .criticalCnt(getCriticalCnt())
      .highCnt(getHighCnt())
      .mediumCnt(getMediumCnt())
      .lowCnt(getLowCnt())
      .noneCnt(getNoneCnt())
      .unknownCnt(getUnknownCnt())
      .totalVuls(getTotalVuls())
      .scannedCnt(getScannedCnt())
      .totalArtifact(getTotalArtifact())
      .fixableCnt(getFixableCnt())
      .dangerousCves(getDangerousCves())
      .dangerousArtifacts(getDangerousArtifacts());
  }


}

