/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StartReplicationExecution
 */
@JsonPropertyOrder({
  StartReplicationExecution.JSON_PROPERTY_POLICY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class StartReplicationExecution {
  public static final String JSON_PROPERTY_POLICY_ID = "policy_id";
  @jakarta.annotation.Nullable
  private Long policyId;

  public StartReplicationExecution() {
  }

  public StartReplicationExecution policyId(@jakarta.annotation.Nullable Long policyId) {
    
    this.policyId = policyId;
    return this;
  }

  /**
   * The ID of policy that the execution belongs to.
   * @return policyId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POLICY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPolicyId() {
    return policyId;
  }


  @JsonProperty(value = JSON_PROPERTY_POLICY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyId(@jakarta.annotation.Nullable Long policyId) {
    this.policyId = policyId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StartReplicationExecution startReplicationExecution = (StartReplicationExecution) o;
    return Objects.equals(this.policyId, startReplicationExecution.policyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StartReplicationExecution {\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private StartReplicationExecution instance;

    public Builder() {
      this(new StartReplicationExecution());
    }

    protected Builder(StartReplicationExecution instance) {
      this.instance = instance;
    }

    public StartReplicationExecution.Builder policyId(Long policyId) {
      this.instance.policyId = policyId;
      return this;
    }


    /**
    * returns a built StartReplicationExecution instance.
    *
    * The builder is not reusable.
    */
    public StartReplicationExecution build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static StartReplicationExecution.Builder builder() {
    return new StartReplicationExecution.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public StartReplicationExecution.Builder toBuilder() {
    return new StartReplicationExecution.Builder()
      .policyId(getPolicyId());
  }


}

