/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Tag
 */
@JsonPropertyOrder({
  Tag.JSON_PROPERTY_ID,
  Tag.JSON_PROPERTY_REPOSITORY_ID,
  Tag.JSON_PROPERTY_ARTIFACT_ID,
  Tag.JSON_PROPERTY_NAME,
  Tag.JSON_PROPERTY_PUSH_TIME,
  Tag.JSON_PROPERTY_PULL_TIME,
  Tag.JSON_PROPERTY_IMMUTABLE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Tag {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_REPOSITORY_ID = "repository_id";
  @jakarta.annotation.Nullable
  private Long repositoryId;

  public static final String JSON_PROPERTY_ARTIFACT_ID = "artifact_id";
  @jakarta.annotation.Nullable
  private Long artifactId;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PUSH_TIME = "push_time";
  @jakarta.annotation.Nullable
  private Date pushTime;

  public static final String JSON_PROPERTY_PULL_TIME = "pull_time";
  @jakarta.annotation.Nullable
  private Date pullTime;

  public static final String JSON_PROPERTY_IMMUTABLE = "immutable";
  @jakarta.annotation.Nullable
  private Boolean immutable;

  public Tag() {
  }

  public Tag id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The ID of the tag
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public Tag repositoryId(@jakarta.annotation.Nullable Long repositoryId) {
    
    this.repositoryId = repositoryId;
    return this;
  }

  /**
   * The ID of the repository that the tag belongs to
   * @return repositoryId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPOSITORY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRepositoryId() {
    return repositoryId;
  }


  @JsonProperty(value = JSON_PROPERTY_REPOSITORY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepositoryId(@jakarta.annotation.Nullable Long repositoryId) {
    this.repositoryId = repositoryId;
  }

  public Tag artifactId(@jakarta.annotation.Nullable Long artifactId) {
    
    this.artifactId = artifactId;
    return this;
  }

  /**
   * The ID of the artifact that the tag attached to
   * @return artifactId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getArtifactId() {
    return artifactId;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTIFACT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArtifactId(@jakarta.annotation.Nullable Long artifactId) {
    this.artifactId = artifactId;
  }

  public Tag name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the tag
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Tag pushTime(@jakarta.annotation.Nullable Date pushTime) {
    
    this.pushTime = pushTime;
    return this;
  }

  /**
   * The push time of the tag
   * @return pushTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PUSH_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getPushTime() {
    return pushTime;
  }


  @JsonProperty(value = JSON_PROPERTY_PUSH_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPushTime(@jakarta.annotation.Nullable Date pushTime) {
    this.pushTime = pushTime;
  }

  public Tag pullTime(@jakarta.annotation.Nullable Date pullTime) {
    
    this.pullTime = pullTime;
    return this;
  }

  /**
   * The latest pull time of the tag
   * @return pullTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PULL_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getPullTime() {
    return pullTime;
  }


  @JsonProperty(value = JSON_PROPERTY_PULL_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPullTime(@jakarta.annotation.Nullable Date pullTime) {
    this.pullTime = pullTime;
  }

  public Tag immutable(@jakarta.annotation.Nullable Boolean immutable) {
    
    this.immutable = immutable;
    return this;
  }

  /**
   * The immutable status of the tag
   * @return immutable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMMUTABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getImmutable() {
    return immutable;
  }


  @JsonProperty(value = JSON_PROPERTY_IMMUTABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImmutable(@jakarta.annotation.Nullable Boolean immutable) {
    this.immutable = immutable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tag tag = (Tag) o;
    return Objects.equals(this.id, tag.id) &&
        Objects.equals(this.repositoryId, tag.repositoryId) &&
        Objects.equals(this.artifactId, tag.artifactId) &&
        Objects.equals(this.name, tag.name) &&
        Objects.equals(this.pushTime, tag.pushTime) &&
        Objects.equals(this.pullTime, tag.pullTime) &&
        Objects.equals(this.immutable, tag.immutable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, repositoryId, artifactId, name, pushTime, pullTime, immutable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tag {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    repositoryId: ").append(toIndentedString(repositoryId)).append("\n");
    sb.append("    artifactId: ").append(toIndentedString(artifactId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pushTime: ").append(toIndentedString(pushTime)).append("\n");
    sb.append("    pullTime: ").append(toIndentedString(pullTime)).append("\n");
    sb.append("    immutable: ").append(toIndentedString(immutable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Tag instance;

    public Builder() {
      this(new Tag());
    }

    protected Builder(Tag instance) {
      this.instance = instance;
    }

    public Tag.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public Tag.Builder repositoryId(Long repositoryId) {
      this.instance.repositoryId = repositoryId;
      return this;
    }
    public Tag.Builder artifactId(Long artifactId) {
      this.instance.artifactId = artifactId;
      return this;
    }
    public Tag.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public Tag.Builder pushTime(Date pushTime) {
      this.instance.pushTime = pushTime;
      return this;
    }
    public Tag.Builder pullTime(Date pullTime) {
      this.instance.pullTime = pullTime;
      return this;
    }
    public Tag.Builder immutable(Boolean immutable) {
      this.instance.immutable = immutable;
      return this;
    }


    /**
    * returns a built Tag instance.
    *
    * The builder is not reusable.
    */
    public Tag build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Tag.Builder builder() {
    return new Tag.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Tag.Builder toBuilder() {
    return new Tag.Builder()
      .id(getId())
      .repositoryId(getRepositoryId())
      .artifactId(getArtifactId())
      .name(getName())
      .pushTime(getPushTime())
      .pullTime(getPullTime())
      .immutable(getImmutable());
  }


}

