/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserGroupSearchItem
 */
@JsonPropertyOrder({
  UserGroupSearchItem.JSON_PROPERTY_ID,
  UserGroupSearchItem.JSON_PROPERTY_GROUP_NAME,
  UserGroupSearchItem.JSON_PROPERTY_GROUP_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UserGroupSearchItem {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_GROUP_NAME = "group_name";
  @jakarta.annotation.Nullable
  private String groupName;

  public static final String JSON_PROPERTY_GROUP_TYPE = "group_type";
  @jakarta.annotation.Nullable
  private Integer groupType;

  public UserGroupSearchItem() {
  }

  public UserGroupSearchItem id(@jakarta.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * The ID of the user group
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }

  public UserGroupSearchItem groupName(@jakarta.annotation.Nullable String groupName) {
    
    this.groupName = groupName;
    return this;
  }

  /**
   * The name of the user group
   * @return groupName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupName() {
    return groupName;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupName(@jakarta.annotation.Nullable String groupName) {
    this.groupName = groupName;
  }

  public UserGroupSearchItem groupType(@jakarta.annotation.Nullable Integer groupType) {
    
    this.groupType = groupType;
    return this;
  }

  /**
   * The group type, 1 for LDAP group, 2 for HTTP group, 3 for OIDC group.
   * @return groupType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getGroupType() {
    return groupType;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupType(@jakarta.annotation.Nullable Integer groupType) {
    this.groupType = groupType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserGroupSearchItem userGroupSearchItem = (UserGroupSearchItem) o;
    return Objects.equals(this.id, userGroupSearchItem.id) &&
        Objects.equals(this.groupName, userGroupSearchItem.groupName) &&
        Objects.equals(this.groupType, userGroupSearchItem.groupType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, groupName, groupType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserGroupSearchItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    groupType: ").append(toIndentedString(groupType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private UserGroupSearchItem instance;

    public Builder() {
      this(new UserGroupSearchItem());
    }

    protected Builder(UserGroupSearchItem instance) {
      this.instance = instance;
    }

    public UserGroupSearchItem.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public UserGroupSearchItem.Builder groupName(String groupName) {
      this.instance.groupName = groupName;
      return this;
    }
    public UserGroupSearchItem.Builder groupType(Integer groupType) {
      this.instance.groupType = groupType;
      return this;
    }


    /**
    * returns a built UserGroupSearchItem instance.
    *
    * The builder is not reusable.
    */
    public UserGroupSearchItem build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static UserGroupSearchItem.Builder builder() {
    return new UserGroupSearchItem.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public UserGroupSearchItem.Builder toBuilder() {
    return new UserGroupSearchItem.Builder()
      .id(getId())
      .groupName(getGroupName())
      .groupType(getGroupType());
  }


}

