/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserSearchRespItem
 */
@JsonPropertyOrder({
  UserSearchRespItem.JSON_PROPERTY_USER_ID,
  UserSearchRespItem.JSON_PROPERTY_USERNAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UserSearchRespItem {
  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nullable
  private Integer userId;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nullable
  private String username;

  public UserSearchRespItem() {
  }

  public UserSearchRespItem userId(@jakarta.annotation.Nullable Integer userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * The ID of the user.
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@jakarta.annotation.Nullable Integer userId) {
    this.userId = userId;
  }

  public UserSearchRespItem username(@jakarta.annotation.Nullable String username) {
    
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(@jakarta.annotation.Nullable String username) {
    this.username = username;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSearchRespItem userSearchRespItem = (UserSearchRespItem) o;
    return Objects.equals(this.userId, userSearchRespItem.userId) &&
        Objects.equals(this.username, userSearchRespItem.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, username);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSearchRespItem {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private UserSearchRespItem instance;

    public Builder() {
      this(new UserSearchRespItem());
    }

    protected Builder(UserSearchRespItem instance) {
      this.instance = instance;
    }

    public UserSearchRespItem.Builder userId(Integer userId) {
      this.instance.userId = userId;
      return this;
    }
    public UserSearchRespItem.Builder username(String username) {
      this.instance.username = username;
      return this;
    }


    /**
    * returns a built UserSearchRespItem instance.
    *
    * The builder is not reusable.
    */
    public UserSearchRespItem build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static UserSearchRespItem.Builder builder() {
    return new UserSearchRespItem.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public UserSearchRespItem.Builder toBuilder() {
    return new UserSearchRespItem.Builder()
      .userId(getUserId())
      .username(getUsername());
  }


}

