/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ryan.openapi.harbor.client.model.WebhookTargetObject;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The webhook policy object
 */
@JsonPropertyOrder({
  WebhookPolicy.JSON_PROPERTY_ID,
  WebhookPolicy.JSON_PROPERTY_NAME,
  WebhookPolicy.JSON_PROPERTY_DESCRIPTION,
  WebhookPolicy.JSON_PROPERTY_PROJECT_ID,
  WebhookPolicy.JSON_PROPERTY_TARGETS,
  WebhookPolicy.JSON_PROPERTY_EVENT_TYPES,
  WebhookPolicy.JSON_PROPERTY_CREATOR,
  WebhookPolicy.JSON_PROPERTY_CREATION_TIME,
  WebhookPolicy.JSON_PROPERTY_UPDATE_TIME,
  WebhookPolicy.JSON_PROPERTY_ENABLED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class WebhookPolicy {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_TARGETS = "targets";
  @jakarta.annotation.Nullable
  private List<WebhookTargetObject> targets = new ArrayList<>();

  public static final String JSON_PROPERTY_EVENT_TYPES = "event_types";
  @jakarta.annotation.Nullable
  private List<String> eventTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_CREATOR = "creator";
  @jakarta.annotation.Nullable
  private String creator;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @jakarta.annotation.Nullable
  private Date creationTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  @jakarta.annotation.Nullable
  private Date updateTime;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public WebhookPolicy() {
  }

  public WebhookPolicy id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The webhook policy ID.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public WebhookPolicy name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of webhook policy.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public WebhookPolicy description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * The description of webhook policy.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public WebhookPolicy projectId(@jakarta.annotation.Nullable Integer projectId) {
    
    this.projectId = projectId;
    return this;
  }

  /**
   * The project ID of webhook policy.
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }

  public WebhookPolicy targets(@jakarta.annotation.Nullable List<WebhookTargetObject> targets) {
    
    this.targets = targets;
    return this;
  }

  public WebhookPolicy addTargetsItem(WebhookTargetObject targetsItem) {
    if (this.targets == null) {
      this.targets = new ArrayList<>();
    }
    this.targets.add(targetsItem);
    return this;
  }

  /**
   * Get targets
   * @return targets
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<WebhookTargetObject> getTargets() {
    return targets;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargets(@jakarta.annotation.Nullable List<WebhookTargetObject> targets) {
    this.targets = targets;
  }

  public WebhookPolicy eventTypes(@jakarta.annotation.Nullable List<String> eventTypes) {
    
    this.eventTypes = eventTypes;
    return this;
  }

  public WebhookPolicy addEventTypesItem(String eventTypesItem) {
    if (this.eventTypes == null) {
      this.eventTypes = new ArrayList<>();
    }
    this.eventTypes.add(eventTypesItem);
    return this;
  }

  /**
   * Get eventTypes
   * @return eventTypes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getEventTypes() {
    return eventTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventTypes(@jakarta.annotation.Nullable List<String> eventTypes) {
    this.eventTypes = eventTypes;
  }

  public WebhookPolicy creator(@jakarta.annotation.Nullable String creator) {
    
    this.creator = creator;
    return this;
  }

  /**
   * The creator of the webhook policy.
   * @return creator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreator() {
    return creator;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreator(@jakarta.annotation.Nullable String creator) {
    this.creator = creator;
  }

  public WebhookPolicy creationTime(@jakarta.annotation.Nullable Date creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

  /**
   * The create time of the webhook policy.
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Date creationTime) {
    this.creationTime = creationTime;
  }

  public WebhookPolicy updateTime(@jakarta.annotation.Nullable Date updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

  /**
   * The update time of the webhook policy.
   * @return updateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(@jakarta.annotation.Nullable Date updateTime) {
    this.updateTime = updateTime;
  }

  public WebhookPolicy enabled(@jakarta.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Whether the webhook policy is enabled or not.
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookPolicy webhookPolicy = (WebhookPolicy) o;
    return Objects.equals(this.id, webhookPolicy.id) &&
        Objects.equals(this.name, webhookPolicy.name) &&
        Objects.equals(this.description, webhookPolicy.description) &&
        Objects.equals(this.projectId, webhookPolicy.projectId) &&
        Objects.equals(this.targets, webhookPolicy.targets) &&
        Objects.equals(this.eventTypes, webhookPolicy.eventTypes) &&
        Objects.equals(this.creator, webhookPolicy.creator) &&
        Objects.equals(this.creationTime, webhookPolicy.creationTime) &&
        Objects.equals(this.updateTime, webhookPolicy.updateTime) &&
        Objects.equals(this.enabled, webhookPolicy.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, projectId, targets, eventTypes, creator, creationTime, updateTime, enabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookPolicy {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("    eventTypes: ").append(toIndentedString(eventTypes)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private WebhookPolicy instance;

    public Builder() {
      this(new WebhookPolicy());
    }

    protected Builder(WebhookPolicy instance) {
      this.instance = instance;
    }

    public WebhookPolicy.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public WebhookPolicy.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public WebhookPolicy.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public WebhookPolicy.Builder projectId(Integer projectId) {
      this.instance.projectId = projectId;
      return this;
    }
    public WebhookPolicy.Builder targets(List<WebhookTargetObject> targets) {
      this.instance.targets = targets;
      return this;
    }
    public WebhookPolicy.Builder eventTypes(List<String> eventTypes) {
      this.instance.eventTypes = eventTypes;
      return this;
    }
    public WebhookPolicy.Builder creator(String creator) {
      this.instance.creator = creator;
      return this;
    }
    public WebhookPolicy.Builder creationTime(Date creationTime) {
      this.instance.creationTime = creationTime;
      return this;
    }
    public WebhookPolicy.Builder updateTime(Date updateTime) {
      this.instance.updateTime = updateTime;
      return this;
    }
    public WebhookPolicy.Builder enabled(Boolean enabled) {
      this.instance.enabled = enabled;
      return this;
    }


    /**
    * returns a built WebhookPolicy instance.
    *
    * The builder is not reusable.
    */
    public WebhookPolicy build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WebhookPolicy.Builder builder() {
    return new WebhookPolicy.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WebhookPolicy.Builder toBuilder() {
    return new WebhookPolicy.Builder()
      .id(getId())
      .name(getName())
      .description(getDescription())
      .projectId(getProjectId())
      .targets(getTargets())
      .eventTypes(getEventTypes())
      .creator(getCreator())
      .creationTime(getCreationTime())
      .updateTime(getUpdateTime())
      .enabled(getEnabled());
  }


}

