/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ryan.openapi.harbor.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The webhook job.
 */
@JsonPropertyOrder({
  WebhookJob.JSON_PROPERTY_ID,
  WebhookJob.JSON_PROPERTY_POLICY_ID,
  WebhookJob.JSON_PROPERTY_EVENT_TYPE,
  WebhookJob.JSON_PROPERTY_NOTIFY_TYPE,
  WebhookJob.JSON_PROPERTY_STATUS,
  WebhookJob.JSON_PROPERTY_JOB_DETAIL,
  WebhookJob.JSON_PROPERTY_CREATION_TIME,
  WebhookJob.JSON_PROPERTY_UPDATE_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class WebhookJob {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_POLICY_ID = "policy_id";
  @jakarta.annotation.Nullable
  private Long policyId;

  public static final String JSON_PROPERTY_EVENT_TYPE = "event_type";
  @jakarta.annotation.Nullable
  private String eventType;

  public static final String JSON_PROPERTY_NOTIFY_TYPE = "notify_type";
  @jakarta.annotation.Nullable
  private String notifyType;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_JOB_DETAIL = "job_detail";
  @jakarta.annotation.Nullable
  private String jobDetail;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @jakarta.annotation.Nullable
  private Date creationTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  @jakarta.annotation.Nullable
  private Date updateTime;

  public WebhookJob() {
  }

  public WebhookJob id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * The webhook job ID.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public WebhookJob policyId(@jakarta.annotation.Nullable Long policyId) {
    
    this.policyId = policyId;
    return this;
  }

  /**
   * The webhook policy ID.
   * @return policyId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POLICY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPolicyId() {
    return policyId;
  }


  @JsonProperty(value = JSON_PROPERTY_POLICY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyId(@jakarta.annotation.Nullable Long policyId) {
    this.policyId = policyId;
  }

  public WebhookJob eventType(@jakarta.annotation.Nullable String eventType) {
    
    this.eventType = eventType;
    return this;
  }

  /**
   * The webhook job event type.
   * @return eventType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }

  public WebhookJob notifyType(@jakarta.annotation.Nullable String notifyType) {
    
    this.notifyType = notifyType;
    return this;
  }

  /**
   * The webhook job notify type.
   * @return notifyType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOTIFY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNotifyType() {
    return notifyType;
  }


  @JsonProperty(value = JSON_PROPERTY_NOTIFY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotifyType(@jakarta.annotation.Nullable String notifyType) {
    this.notifyType = notifyType;
  }

  public WebhookJob status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * The webhook job status.
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }

  public WebhookJob jobDetail(@jakarta.annotation.Nullable String jobDetail) {
    
    this.jobDetail = jobDetail;
    return this;
  }

  /**
   * The webhook job notify detailed data.
   * @return jobDetail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_JOB_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobDetail() {
    return jobDetail;
  }


  @JsonProperty(value = JSON_PROPERTY_JOB_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobDetail(@jakarta.annotation.Nullable String jobDetail) {
    this.jobDetail = jobDetail;
  }

  public WebhookJob creationTime(@jakarta.annotation.Nullable Date creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

  /**
   * The webhook job creation time.
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Date creationTime) {
    this.creationTime = creationTime;
  }

  public WebhookJob updateTime(@jakarta.annotation.Nullable Date updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

  /**
   * The webhook job update time.
   * @return updateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(@jakarta.annotation.Nullable Date updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookJob webhookJob = (WebhookJob) o;
    return Objects.equals(this.id, webhookJob.id) &&
        Objects.equals(this.policyId, webhookJob.policyId) &&
        Objects.equals(this.eventType, webhookJob.eventType) &&
        Objects.equals(this.notifyType, webhookJob.notifyType) &&
        Objects.equals(this.status, webhookJob.status) &&
        Objects.equals(this.jobDetail, webhookJob.jobDetail) &&
        Objects.equals(this.creationTime, webhookJob.creationTime) &&
        Objects.equals(this.updateTime, webhookJob.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, policyId, eventType, notifyType, status, jobDetail, creationTime, updateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookJob {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    notifyType: ").append(toIndentedString(notifyType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    jobDetail: ").append(toIndentedString(jobDetail)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private WebhookJob instance;

    public Builder() {
      this(new WebhookJob());
    }

    protected Builder(WebhookJob instance) {
      this.instance = instance;
    }

    public WebhookJob.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public WebhookJob.Builder policyId(Long policyId) {
      this.instance.policyId = policyId;
      return this;
    }
    public WebhookJob.Builder eventType(String eventType) {
      this.instance.eventType = eventType;
      return this;
    }
    public WebhookJob.Builder notifyType(String notifyType) {
      this.instance.notifyType = notifyType;
      return this;
    }
    public WebhookJob.Builder status(String status) {
      this.instance.status = status;
      return this;
    }
    public WebhookJob.Builder jobDetail(String jobDetail) {
      this.instance.jobDetail = jobDetail;
      return this;
    }
    public WebhookJob.Builder creationTime(Date creationTime) {
      this.instance.creationTime = creationTime;
      return this;
    }
    public WebhookJob.Builder updateTime(Date updateTime) {
      this.instance.updateTime = updateTime;
      return this;
    }


    /**
    * returns a built WebhookJob instance.
    *
    * The builder is not reusable.
    */
    public WebhookJob build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WebhookJob.Builder builder() {
    return new WebhookJob.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WebhookJob.Builder toBuilder() {
    return new WebhookJob.Builder()
      .id(getId())
      .policyId(getPolicyId())
      .eventType(getEventType())
      .notifyType(getNotifyType())
      .status(getStatus())
      .jobDetail(getJobDetail())
      .creationTime(getCreationTime())
      .updateTime(getUpdateTime());
  }


}

